release-plz/release-plz

Dockerfile
=> fix: docker image can run `release` command

crates/git_cmd/src/lib.rs
After I have introduced a symlink in this repo, release-plz has started failing. See [here](https://github.com/MarcoIeni/release-plz/commit/832838b7735d03045887f1ddf0187268100c69a0).
I am excluding symlink from `git status` check
=> fix: filter symlink when checking if repo is clean

Cargo.lock, crates/next_version/Cargo.toml, crates/next_version/src/version_increment.rs
`cargo-edit` brought a lot of dependencies for 3 fairly easy functions.
Their inlined versions are still easy to read and extend if necessary.
=> refactor: inline the increment* functions to cut down dependencies

crates/release_plz_core/src/diff.rs
Fixed typos via running `codespell -L crate crates/ -w`
=> Fix typo in code comment

crates/release_plz/src/args/update.rs
While running `release-plz generate-completions`, I got the following error:
```
thread 'main' panicked at 'Command::get_arg_conflicts_with: The passed arg conflicts with an arg unknown to the cmd', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.18/src/builder/command.rs:3493:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is due to the recent [clap v4 upgrade](https://github.com/MarcoIeni/release-plz/commit/e4401a5a28de0af31e313b2cfeae1d8210d5875f). It is stated in the [changelog](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md) that arguments should be used as verbatim casing for `conflicts_with` and `requires`:
> *(derive)* Leave `Arg::id` as `verbatim` casing, requiring updating of string references to other args like …
=> Use the correct case for conflicting arguments

crates/release_plz/src/args/release_pr.rs
=> fix: reintroduce github-token flag

Cargo.lock, crates/cargo_utils/CHANGELOG.md, crates/cargo_utils/Cargo.toml, crates/release_plz_core/Cargo.toml, crates/test_logs/CHANGELOG.md, crates/test_logs/Cargo.toml
* `cargo_utils`: 0.1.4 -> 0.1.5
* `test_logs`: 0.1.10 -> 0.1.11
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
=> chore: release

Cargo.lock, Cargo.toml, crates/release_plz_core/Cargo.toml, crates/release_plz_core/src/backend.rs, crates/release_plz_core/src/gitea_client.rs, crates/release_plz_core/src/github_client.rs, crates/release_plz_core/src/release.rs
Reasons:
- it removes 18 dependencies 
- it unblocks https://github.com/MarcoIeni/release-plz/issues/420
- we support Gitea, too and the APIs are almost the same. So we need to implement the HTTP calls manually anyway
- we can implement a retry mechanism easily with `reqwest-middleware` for both gitea and github
=> chore: remove `octocrab` dependency

.gitignore, crates/release_plz_core/src/next_ver.rs
- ignore vendor directory
- rename github repo field
=> chore: rename field

crates/git_cmd/src/lib.rs, crates/release_plz_core/src/release_pr.rs
[This](https://github.com/MarcoIeni/release-plz/commit/55172e4b4bfe9e01a6f8bbddc410783521cd0e90) commit failed because there were merge conflicts when doing `git stash pop`.
We only do `git stash pop` when the PR wasn't edited by a human, so it's fine to overwrite the changes made by bots (including release-plz itself).
=> fix: force git stash

crates/release_plz/src/args/release.rs, crates/release_plz/src/args/release_pr.rs, crates/release_plz_core/src/backend.rs
It's not supported yet. We don't want to show it in the help menu.
=> chore: remove gitlab from release-pr backend

crates/git_cmd/src/lib.rs, crates/release_plz_core/src/repo_url.rs
=> fix: use default origin for repository url

crates/release_plz_core/src/backend.rs, crates/release_plz_core/src/release_pr.rs
=> fix: read opened PRs with empty body

.github/mergify.yml
This change has been made by @MarcoIeni from Mergify config editor.
=> chore(mergify): don't update dependabot PRs

crates/git_cmd/src/lib.rs
By changing the formatting the whole raw commit message is returned by `git log`.This way when determining the next version in `NextVersionFromDiff` (without semverchecK), commits with `Breaking Version` footers now also lead to a major version bump.
This fixes #687 .
=> fix: read full commit message

crates/release_plz_core/src/release.rs
The loop over all release artefacts should not return when it finds a crate that is already published but instead continue to evaluate all other to-be-released artefacts.
=> fix: don't return early when publishing crates

.github/workflows/docker.yml
Tried building `release-plz` in mac m1 arm and it succeeded, so I am guessing linux arm also should succeed
=> chore: enable docker builds for arm

docs/src/installation.md
`release-plz` is moved to the community repository: https://archlinux.org/packages/community/x86_64/release-plz/
=> chore(docs): update installation instructions for Arch Linux

crates/release_plz_core/src/command/update.rs
=> fix(workspaces): report correct version update

crates/git_cmd/src/lib.rs, crates/release_plz_core/src/next_ver.rs
=> chore: stop looking at git history if commit tagged

crates/release_plz_core/src/lock_compare.rs
=> fix: ignore Cargo.lock dev dependencies changes

Cargo.lock, Cargo.toml, crates/release_plz_core/Cargo.toml, crates/release_plz_core/src/cargo.rs, crates/release_plz_core/src/command/release.rs
Adds support for sparse registry URLs, fixes #831.
=> feat(release): add support for sparse registry URLs

website/package-lock.json, website/package.json
- Revert "build(deps): bump clsx from 1.2.1 to 2.0.0 in /website (#878)"
- Revert "build(deps): bump prism-react-renderer from 1.3.5 to 2.0.6 in /website (#879)"
- Revert "build(deps): bump @mdx-js/react from 1.6.22 to 2.3.0 in /website (#893)"
=> fix: revert website breaking changes

crates/release_plz_core/src/changelog.rs, crates/release_plz_core/src/diff.rs, crates/release_plz_core/src/next_ver.rs, crates/release_plz_core/src/version.rs
Resolves #954 
This change passes the commit IDs to `git-cliff` when the changelog is generated, allowing users to use commit IDs in their changelog formats.
When using a commit message without an actual commit, I changed the placeholder value to "N/A", indicating there is no corresponding commit ID available. Happy to discuss this further if you'd like to handle this case differently.
=> feat: pass commit ids to git-cliff

website/docs/usage/release.md
Add release subcommand usage on Gitlab, detailing the required arguments and scopes required for Gitlab access token.
Closes #847.
=> docs: add release subcommand usage on Gitlab

README.md, website/docs/changelog-format.md, website/docs/config.md, website/docs/faq.md, website/docs/intro.md, website/src/components/HomepageFeatures/index.js
This PR updates the `git-cliff` links to use the website instead of the repo when applicable.
=> docs: update git-cliff links

.github/workflows/cd.yml, release-plz.toml
This reverts commit 8398a329aa70a8495bc68b59eeae49c23defa66e.
You can't trigger github actions on draft releases.
=> Revert "chore(ci): publish release after binary upload (#990)"

website/docs/github/trigger.md
As described in #999, slightly improve the (website) docs https://release-plz.ieni.dev/docs/github/trigger#use-a-github-action of how to use a GitHub ~~Action~~ App
- add example of App name `release-plz[bot]`
- mention permissions for protected tags
- describe optionally creating a private App
- use official GitHub `actions/create-github-app-token` action
=> Improve docs on how to use a GitHub App

crates/release_plz_core/src/command/release.rs
The `registry` argument was not being used when calling `cargo publish`, causing it to try to publish to `crates.io` even when a different registry was passed.
=> fix: use registry argument on publish

crates/release_plz/src/args/mod.rs
Keeping configuration in dotfiles is often desirable. This PR supports a root `.release-plz.toml` config file if `release-plz.toml` is not found.
If you'd rather this be considered supported already through the `config` CLI arg then I would understand, but would also suggest adding support for that arg to the GH action.
=> feat: support .release-plz.toml as a config file

website/docs/config.md
Follow up to #1057 where I forgot to add the website docs.
=> docs: add documentation for dot config

crates/release_plz/tests/all/changelog.rs, crates/release_plz_core/src/next_ver.rs, crates/release_plz_core/src/repo_url.rs, website/docs/usage/release.md, website/docs/usage/shell-completion.md, website/docs/usage/update.md
=> docs: document Gitea releases

crates/cargo_utils/src/registry.rs
As discussed with @MarcoIeni, this TODO is not applicable.
Users can set their own registry through the configuration.
=> Local registries are already supported

crates/release_plz_core/src/command/release.rs, crates/release_plz_core/src/next_ver.rs, fixtures/typo-in-overrides/Cargo.toml
=> Prevent typos in overrides

crates/release_plz_core/src/changelog_parser.rs
I ran into an issue on Windows where the header would be added (but not replaced\removed) on each update.
This is because the line `## [Unreleased]` would end with CRLF but the code would assume it was LF.
So when the `prepend` function in git-cliff would be called, the `replacen` function would not get a match.
Here is a screenshot of the generated file showing the characters:
I added a test too!
=> fix: resolve issue on Windows machines that use CRLF that would duplicate the header on each update

crates/release_plz_core/src/next_ver.rs
There is no need to for filtering for the commits description, as git-cliff splits the commit internally into description, body and footer.
Thus I removed the filter.
=> fix: pass full commit message to git-cliff (#1103)

crates/release_plz/src/args/release.rs, crates/release_plz/src/args/release_pr.rs
Fixes this security issue:
```sh
$ GIT_TOKEN=pwned release-plz release-pr --help
Options:
...
--git-token <GIT_TOKEN>
Git token used to create the pull request [env: GIT_TOKEN=pwned] [aliases: github-token]
```
=> chore(args): hide the environment value of git token

Cargo.lock, Cargo.toml, crates/release_plz_core/src/clone/mod.rs
This will allow pulling crates from registries that require authentication without needing unstable options.
The [functionality was stabilized][1] in November with the release of Rust 1.74.0. This simply bumps the dependency and fixes some relocated imports.
[1]: https://blog.rust-lang.org/2023/11/16/Rust-1.74.0.html#cargo-registry-authentication
=> build(deps): bump cargo to 0.75.1

crates/release_plz/src/config.rs, crates/release_plz/src/main.rs
=> chore: flatten part of config struct

crates/release_plz_core/src/command/update.rs
Changed the update command to use cargo metadata from the tmp manifest, which give it the correct dependency paths used for comparison during dependency updates.
=> fix: Correct dependency update behavior for release-pr

crates/release_plz/src/config.rs, crates/release_plz_core/src/command/release.rs, crates/release_plz_core/src/git/backend.rs, website/docs/config.md
Closes #678 
This pull request adds the ability to set a release type mode for GitHub and Gitea. It uses the modes which where defined beforehand:
- Prod: ready for production
- Pre: pre-release
- Auto: pre-release detection based on a semver version within the git tag
=> feat: add pre-release option

crates/release_plz_core/src/command/update.rs
We've encountered issues when [using release-plz at lumina](https://github.com/eigerco/lumina/actions/runs/7783144141/job/21220976044#step:5:225). It seems like currently `release-plz` is capable of updating dependencies specified directly in packages' manifests and is ignoring dependencies specified on workspace level. The latter doesn't get version bumps which results in failures in resolving.
I'm not sure if there are additional things needed when updating also workspace-wide dependencies tho. Let me know wdyt
=> fix: update local dependencies specified in the workspace manifest

.schema/latest.json, crates/release_plz/src/config.rs, crates/release_plz/tests/all/helpers/gitea/gitea_client.rs, crates/release_plz/tests/all/release.rs, crates/release_plz_core/src/command/release.rs, crates/release_plz_core/src/git/backend.rs, crates/release_plz_core/src/next_ver.rs, website/docs/config.md
This PR add custom git release name feature (https://github.com/MarcoIeni/release-plz/issues/677) :
- setting global by git-release-name field in workspace
- override in each project by git-release-name field
Default:
- `{{ package }}-{{ version }}` for workspace 
- `v{{ version }}` for single project 
Ps: Only Project.release_name is tested, maybe we need some way to test it but I don'f familiar with GitTea for adding more tests.
=> feat: custom git-release-name by tera template. #677

website/docs/config.md
=> docs: remove left-over raw string literals

crates/release_plz/Cargo.toml, crates/release_plz_core/Cargo.toml
This adds the ability to build against system libraries like libgit2 and OpenSSL, when the feature is not present.
=> feat: add `all-static` feature

.schema/latest.json, crates/release_plz/src/args/update.rs, crates/release_plz/src/config.rs, crates/release_plz/tests/all/changelog.rs, crates/release_plz_core/src/diff.rs, crates/release_plz_core/src/next_ver.rs, website/docs/config.md
Prepare release only if at least one commit matches a certain regex
Close https://github.com/MarcoIeni/release-plz/issues/1274
=> 1274 prepare release if commit match regex

.github/workflows/cd.yml, .github/workflows/ci.yml, website/docs/extra/releasing-binaries.md
=> chore(ci): remove support for universal mac app

crates/git_cmd/src/lib.rs, crates/release_plz/src/args/update.rs, crates/release_plz/tests/all/helpers/test_context.rs, crates/release_plz_core/src/next_ver.rs
Close https://github.com/MarcoIeni/release-plz/issues/1286
=> chore: error if committed Cargo.lock is in `.gitignore`

tests/docker-compose.yml
This partially fixes issue #1318 (containers can now be started with podman, but the actual tests still don't pass for unknown reason).
=> fix: Fix starting containers with podman

.schema/latest.json, crates/release_plz/src/args/release.rs, crates/release_plz/src/config.rs, crates/release_plz_core/src/command/release.rs, website/docs/config.md
feat: Add `publish_features` to pass feature list to `cargo publish`
This implements issue #1308
This is useful to avoid having to use `publish_no_verify` for packages that need at least some features enabled.
I believe the changes are relatively straightforward. I cannot properly test this due to issue #1318  though. I also didn't see any end-to-end tests for the existing `publish_no_verify` so that hasn't been added. I just added the equivalent tests of `publish_no_verify` that I could find.
=> feat: Add `publish_features` to pass feature list to `cargo publish`

crates/git_cmd/src/lib.rs, crates/release_plz_core/src/next_ver.rs, crates/release_plz_core/src/package_compare.rs
Close https://github.com/MarcoIeni/release-plz/issues/1309
ISSUE:
- `git checkout` to the commits of the readme
- compare the changes
- add the commit if they differ and if the commit isn't present yet.
=> fix: check diffs in README

crates/cargo_utils/src/workspace_members.rs, crates/release_plz/src/args/repo_command.rs
=> chore: improve error message to suggest `--project-manifest`

crates/release_plz_core/src/package_compare.rs
See #1360
> Possible solutions:
>
> - return true if `cannot compare README files` and emit a warning. Probably this is the best short-term solution,
=> chore: emit a warning on readme file mismatch

website/docs/usage/installation.md
I packaged `release-plz` for Alpine Linux and this PR simply adds instructions :bear:
=> docs(installation): add instructions for Alpine Linux

website/docs/extra/single-tag.md
I copied this example into a project and [release-plz tried to use the literal `v${version}` as a tag][1], since `${}` is not how tera does variables.
[1]: https://github.com/obmarg/cynic/blame/2a0c2b2db127993aa88e78b75b998ae70b2e2c47/CHANGELOG.md#L12
=> docs: fix the single git tag config example

crates/release_plz/src/args/mod.rs, crates/release_plz/src/args/release.rs, crates/release_plz/src/args/repo_command.rs, crates/release_plz/src/args/update.rs, crates/release_plz_core/src/next_ver.rs, crates/release_plz_core/tests/all/helpers/comparison_test.rs
Close https://github.com/MarcoIeni/release-plz/issues/1333
=> chore: rename `--project-manifest` to `--manifest-path` in error messages

crates/release_plz_core/src/cargo.rs, crates/release_plz_core/src/command/release.rs
=> fix: use token to fetch sparse metadata

crates/git_cmd/src/lib.rs, crates/release_plz_core/src/command/release_pr.rs
When updating PR on github, force push the rebased branch first and create commit through API to keep the verified status of the commit.
Fixes #1406
=> fix: updating pr persists gh verified status

Cargo.lock, Cargo.toml, crates/git_cmd/src/lib.rs, crates/release_plz_core/Cargo.toml, crates/release_plz_core/src/command/release_pr.rs, crates/release_plz_core/src/git/github_graphql.rs
Fixes #1487 
Force pushing a branch that links to an open PR with the content of a base branch automatically closes it. To prevent that we create a new temporary branch for release, commit there and then force push original one.
=> fix(#1487): don't close release PR on force-push

crates/release_plz/src/main.rs
Extracted from https://github.com/MarcoIeni/release-plz/pull/1521
=> fix: release command if `-o` isn't specified

crates/release_plz/src/args/release.rs, crates/release_plz/src/main.rs, crates/release_plz_core/src/git/backend.rs, crates/release_plz_core/src/git/gitlab_client.rs, crates/release_plz_core/src/repo_url.rs, website/docs/usage/release.md
- Add support for on-premise hosted GitLab, not only gitlab.com
- Add support for SSH git repositories -> will be converted to "https" API URL
- Add support for multi level gitlab groups
- Respect upper case PRIVATE-TOKEN header
- Mark PRIVATE-TOKEN header value as sensitive
- fix bug: release-plz release fails when no "-o json" given as argument
=> feat(backend): GitLab on-premise support and multilevel URLs, SSH git repos

crates/release_plz/src/config.rs, crates/release_plz_core/src/command/release.rs
related to https://github.com/MarcoIeni/release-plz/issues/1549
=> fix(release): don't try to parse changelog if it doesn't exist

CONTRIBUTING.md, crates/release_plz_core/src/command/release_pr.rs, crates/release_plz_core/src/git/backend.rs, crates/release_plz_core/src/pr.rs, crates/test_logs/src/lib.rs
Closes https://github.com/MarcoIeni/release-plz/issues/1582
I tested this manually in my repo here: https://github.com/elastio/bon/pull/46.
While testing it I mistakenly tried to run `release-pr` command from the branch that doesn't exist on remote. `release-plz` was subsequently returning an error that didn't actually say what the problem was. It just said that it failed to open a PR with status `422`. I improved the error rendering for the `GitClient` by outputting the response body as well which contained the detail that `base` field of the PR was not valid.
=> Add version of the packages into PR name if they all use the same

.github/workflows/ci.yml
=> chore: ignore rust ci when editing js and ts files

.github/workflows/deny.yml
=> fix(ci): don't run cargo-deny twice in CI

Cargo.toml, crates/release_plz_core/src/cargo.rs
=> fix: fallback to http 1.1 when http2 is not supported on fetching sparse metadata

.schema/latest.json, crates/release_plz/src/config.rs, crates/release_plz/tests/all/release_pr.rs, crates/release_plz_core/src/next_ver.rs, crates/release_plz_core/src/version.rs, website/docs/config.md
When enabled (off by default), it triggers a minor version bump for `feat` commits even when the baseline version is 0.x.
This implements the feature requested in #1656.
=> feat: Add `features_always_increment_minor` flag

Cargo.toml
In order to make the rust-url compatible with no_std, the crate needs to introduce a `std` feature and make it default. See https://github.com/servo/rust-url/pull/831.
To reduce impact, downstream libraries should leave url's default features enabled (no other features are currently `default`).
=> Enable default features for url crate

Cargo.lock, Cargo.toml, crates/cargo_utils/Cargo.toml, crates/cargo_utils/src/lib.rs, crates/cargo_utils/src/registry.rs, crates/cargo_utils/src/token.rs, crates/release_plz/src/args/release.rs, crates/release_plz/src/args/update.rs, crates/release_plz_core/Cargo.toml, crates/release_plz_core/src/cargo.rs, crates/release_plz_core/src/clone/source.rs, crates/release_plz_core/src/command/release.rs, crates/release_plz_core/src/download.rs, crates/release_plz_core/src/registry_packages.rs, website/docs/github/quickstart.md
tokens are read from:
- cli's argument `--token`
- environment variables (ala `cargo:token`)
- file `cargo/credentials.toml` (ala `cargo:token`)
Also registry + token is read for each package because:
- each package could be published to a different registry, 
- `--registry` and `--token` could be unspecified (in this case use info from `Cargo.toml` ,...)
FIX #1659
=> fix: retrieve token for each package's registry ala `cargo:token`

Cargo.toml, crates/release_plz_core/src/pr.rs
As described in #1715, some workspaces may have enough changes to publish that trying to open a PR fails because the body is too long. This PR adds a configuration option to disable adding the changelog to the PR body, leaving only the changes summary.
One alternative would be to let the user specify whether they want to include the changelog in the PR body for each package. Another would be to forgo adding a user option and automatically fail over to the summary-only body if we detect that the body is too long.
Closes #1715.
=> fix: Disable changelog in PR body if it goes over github character limit

.schema/latest.json, crates/release_plz/src/args/release.rs, crates/release_plz/src/args/update.rs, crates/release_plz/src/config.rs, crates/release_plz/src/main.rs, crates/release_plz/tests/all/helpers/test_context.rs, crates/release_plz_core/src/command/release.rs, crates/release_plz_core/src/command/release_pr.rs, crates/release_plz_core/src/lib.rs, crates/release_plz_core/src/pr.rs, website/docs/config.md
Fix for Issue # 1728  - Changes related to configuring the PR Branch Prefix in release-plz.toml (defaults to the current prefix "release-plz-" if none specified)
=> feat: add `pr_branch_prefix` option to configure branch prefix for release-pr (#1728)

.schema/latest.json, crates/release_plz/src/config.rs, crates/release_plz/src/main.rs, crates/release_plz/tests/all/release_pr.rs, crates/release_plz_core/src/command/release_pr.rs, crates/release_plz_core/src/command/update.rs, crates/release_plz_core/src/pr.rs, crates/release_plz_core/src/tera.rs, website/docs/config.md
=> feat: add pr_body field

crates/release_plz/src/args/mod.rs
There was a small typo in command-line help about log level adjustment (correct environment variable is `RUST_LOG`.
=> fix: typo in CLI log level help

.github/workflows/cd.yml, .github/workflows/ci.yml, website/docs/extra/releasing-binaries.md
github will remove macos-12 soon
=> chore(ci): bump macos version

crates/release_plz_core/src/next_ver.rs
Close https://github.com/MarcoIeni/release-plz/issues/1791
=> fix: revert Cargo.lock changes after running `cargo package`

crates/release_plz_core/src/git/backend.rs
The response for `/api/v4/projects/:id/merge_requests/:merge_request_iid/commits` is described [in the documentation], and includes neither a `sha`, nor an `author` field.
[in the documentation]: https://docs.gitlab.com/ee/api/merge_requests.html#get-single-merge-request-commits
[As far as I can tell](https://github.com/MarcoIeni/release-plz/blob/7ef73f07dfce9fbf6a214bf1cbc2cab412155443/crates/release_plz_core/src/git/backend.rs#L570-L596) the `GitLabMrCommit` is only parsed from the `/api/v4/projects/:id/merge_requests/:merge_request_iid/commits` route, so the fields that are parsed have to be adjusted.
I  removed the author information, because the route described only gives `{author,committer}_name`, and `{author,committer}_email`, which are taken from the commit, and do not correlate …
=> fix: Correctly deserialize GitLab MR commits

crates/release_plz_core/src/project.rs
Implements #1763: adds additional check for `release-plz init` that ensures all local dependencies have a version specified. Specifying `version = "*"` is treated like having no version specified, which follows the behavior of cargo.
Closes #1763.
=> feat(init): check if Cargo.toml constains the `version` field in local dependencies

crates/release_plz/src/args/repo_command.rs
Added a lifetime to the return type of `user_repo_url` trait func. The compiler requires explicit lifetimes because the function takes references from both `self` and `config`, and it cannot safely infer which input's lifetime the output depends on.
=> Fix elided lifetime issue

crates/release_plz_core/src/git/backend.rs, website/docs/config.md
See <https://docs.gitlab.com/ee/api/merge_requests.html#update-mr>.
Use the [GitLab Merge Request API](https://docs.gitlab.com/ee/api/merge_requests.html#update-mr) to add the labels to the merge request.
It is also possible to add the labels on merge request creation, but to keep the program flow the same, I have decided to use the "update an existing merge request" endpoint to match the GitHub version.
I decided to use the `add_labels` parameter instead of `labels`, since the `labels` parameter can be destructive (in the sense that it can remove labels from a merge request).
I have tested this successfully in a private GitLab repo, and can't think of a way to add automated testing for this.
=> feat: Enable `pr_labels` for GitLab backend

crates/release_plz_core/src/project.rs
Fix bug described in https://github.com/release-plz/release-plz/pull/1855
=> fix: locate Cargo.lock correctly when project isn't in root directory

crates/release_plz_core/src/next_ver.rs
Check if the current version is a pre-release version and if yes bump the pre-release version instead of the patch version when the dependencies of the crate have changed.
Fixes #1914
=> fix: increment pre-release version correctly when deps change

.github/workflows/cargo-assist.yml, .github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/release-plz.yml, crates/release_plz/tests/all/release_pr.rs
This pull request updates the `release-plz` CI workflow to replace the use of `dtolnay/rust-toolchain` with `actions-rust-lang/setup-rust-toolchain`. This change provides several advantages, including:
- **Caching support:** Speeds up CI runs by utilizing Rust cache effectively.
- **Support for `rust-toolchain` file:** Automatically picks the Rust version specified in the `rust-toolchain` file.
- **Ability to pin to a specific commit:** Ensures stability in CI environments.
- **Problem matcher integration:** Improves developer experience by highlighting errors inline in GitHub.
1. Updated the `Install Rust toolchain` step in the `release-plz-release` and `release-plz-pr` jobs to use `actions-rust-lang/setup-rust-toolchain@<latest-commit-sha>`.
2. Pinned the action to a specific commit SHA …
=> chore: update release-plz CI to use actions-rust-lang/setup-rust-toolchain

crates/release_plz/tests/all/helpers/gitea/gitea_new.rs, crates/release_plz/tests/all/release_pr.rs, crates/release_plz_core/src/command/release_pr.rs, crates/release_plz_core/src/git/backend.rs, crates/release_plz_core/src/git/gitea_client.rs, website/docs/config.md, website/docs/usage/release-pr.md, website/docs/usage/release.md
Close [#1881](https://github.com/release-plz/release-plz/issues/1881)
1. Fixed Typo in Struct Name:
- Renamed the struct GiteaRelase to GiteaRelease to correct a spelling error.
2. Pull Request Labels Management:
- New Structs and Fields:
- Introduced a Label struct with name and ID fields.
- Added a labels field to existing structs like GitPr and GitLabMr to accommodate label information.
- Label Validation:
- Implemented validation to ensure label names are non-empty and do not exceed 50 characters, providing appropriate error messages for invalid inputs.
- Gitea Integration:
- Introduced a GiteaLabelResponseStruct to handle responses from Gitea's label API.
- Enhanced label management for Gitea backends by:
-   Fetching existing labels.
-   Creating new labels if they don't exist.
- …
=> feat: allow adding labels to Gitea release PR

crates/release_plz/tests/all/release_pr.rs
The `release-pr` tests check the contents of the opened PR, which are generated from the changelogs. The changelogs specify the release date in UTC:
https://github.com/release-plz/release-plz/blob/c633007e752ba3d127af03e4c18b4fa5b7fdf1fc/crates/release_plz_core/src/changelog.rs#L321-L327
However, the release-pr test compares this UTC date to a date obtained from the local timezone. If the local timezone is not UTC and is at a different date than UTC, then this can cause issues.
=> fix: Make release-pr tests Use UTC rather than local timezone

clippy.toml, crates/release_plz_core/src/command/update.rs, crates/release_plz_core/src/fs_utils.rs, crates/release_plz_core/src/next_ver.rs, crates/release_plz_core/src/package_path.rs, crates/release_plz_core/src/project.rs
The previous implementation of `PackagePath::canonicalize` was not using `dunce::canonicalize`. This lead to Package::dependencies_to_update comparing a dunce canonicalized path to a std::fs canonicalized path.
On Windows, the former would rarely add the extended length prefix, but the latter always added the extended path length prefix. This led to `next_ver::is_dependency_referred_to_package` always returning false on Windows, causing versioned path dependencies not being updated.
=> fix(core): Use dunce to canonicalize package paths

crates/git_cmd/src/lib.rs
Adds a method to retrieve all git tags in a repository.
=> feat(git_cmd): Add `Repo::get_all_tags`

crates/release_plz_core/src/command/release.rs
When `--dry-run` is specified, prints (by adding `tracing` events) the steps that `release` would have taken, such as git tag and release creation.
=> fix(core): Make `release --dry-run` more informative

crates/release_plz_core/src/next_ver.rs
When obtaining the next versions of the workspace, if `allow_dirty` is set to true and the repository is dirty, we commit the uncommitted changes so that they can easily be restored without being lost with a `checkout_head` (which happens a couple times during the diff process).
Note that this commit is only made in the `TempRepo` made by `Project::get_repo`, and the user's original repo remains untouched.
As per the recommendation in https://github.com/release-plz/release-plz/pull/1982#issuecomment-2601007848, this was changed to _stash_ the uncommitted changes rather than commit them.
=> fix(core): Stash uncommited changes in dirty repos during update

crates/release_plz_core/src/clone/mod.rs, crates/release_plz_core/src/download.rs
Refactors the `clone::Cloner` implementation to allow for retrieving the intermediary `IndexSummary`s when looking up the latest version of a package in a Cargo registry. 
This allows us to query published package metadata (such as name and version) from the `IndexSummary` without having to download the entire package, thereby letting us defer the package download.
=> allow fetching latest package summaries from cargo registry

crates/release_plz_core/src/next_ver.rs
the git error from call to `checkout_last_commit_at_paths` shouldn't be silenced. Fix : #1960
If the git repository files are corrupted, we need to have an error.
I have tried to reproduce a case where we can have an error from `checkout_last_commit_at_paths` because of no commit to include in diff, but without success, to get the `there are no commits` as valid message.
=> fix: don't suppress git error when determining commits to release

crates/release_plz_core/src/registry_packages.rs
Primarily looking at Pavex here, where downloading packages takes several seconds.
=> feat: Download packages from different registries in parallel to improve performance

crates/release_plz/tests/all/release_pr.rs, crates/release_plz_core/src/command/release_pr.rs, crates/release_plz_core/src/command/update.rs, crates/release_plz_core/src/pr.rs, website/docs/config.md
closes #1788 
1. Moved the default PR body template to a constant
2. Using Tera templating  for both default and custom templates
3. Simplifying the `pr_body_default` function
=> ♻️ refactor: use tera template for default PR body

crates/release_plz_core/src/changelog_filler.rs
I kept running into this issue in Pavex ([example](https://github.com/LukeMathWalker/pavex/actions/runs/13078673274/job/36496954617)), so I finally set down to investigate it.
I confirm that with this fix it now runs successfully (e.g. [this PR](https://github.com/LukeMathWalker/pavex/pull/432) was opened running the patched version locally).
=> fix: Don't try to fetch information from the remote if it's a "filler" commit

.github/workflows/release-plz.yml
There was an error when running `release-plz release` in [ci](https://github.com/release-plz/release-plz/actions/runs/13090238728/job/36526035567):
```
Error: can't determine registry indexes
Caused by:
0: "gix" crate failed. If problems persist, consider deleting `~/.cargo/registry/index/github.com-1ecc6299db9ec823/`
1: Refusing to initialize the non-empty directory as '/home/runner/.cargo/registry/index/github.com-1ecc6299db9ec823'
```
maybe this is due to issues with caching.
=> chore(ci): don't use caching when running release-plz

crates/cargo_utils/src/registry.rs, crates/release_plz_core/src/command/release.rs
Attempts to loop up a `CARGO_REGISTRIES_<name>_INDEX` env var as the highest priority override for registry indexes falling back to the cargo config hierarchy if not present.
closes #2032
=> fix: support env var override for registry index

Cargo.lock, Cargo.toml, crates/release_plz/Cargo.toml, crates/release_plz/src/args/mod.rs, crates/release_plz/src/log.rs, crates/release_plz/src/main.rs, crates/release_plz/tests/all/helpers/test_context.rs, website/docs/troubleshooting.md
Addresses parts of https://github.com/release-plz/release-plz/issues/2060
- Use RELEASE_PLZ_LOG env var to control logging level
- ~Use clap-verbosity-flag to add --verbose and --quiet flags to the cli~
- Fallback to RUST_LOG if RELEASE_PLZ_LOG is not set (for backwards
compatibility)
- Remove "pretty" styled logs - these make the logs harder to read as
when viewing them in a github action as the information is split over
multiple lines
- Use simpler tracing_subscriber config (`fmt()` and `init()`)
- Remove tracing-log dependency (this is enabled by default by `init()`)
---
As a side note, I'd generally suggest that keeping the target on by default is a good thing to do as knowing where a log message comes from is one of the main things a log output should tell you. I haven't made that …
=> chore: simplify logging setup

crates/release_plz/tests/all/changelog.rs, crates/release_plz/tests/all/helpers/mod.rs, crates/release_plz/tests/all/helpers/test_context.rs, crates/release_plz/tests/all/release_pr.rs, crates/release_plz_core/src/diff.rs, crates/release_plz_core/src/lib.rs
`(#xxx)` in changelog is replaced with `([#xxx](https://github.com/release-plz/release-plz/pull/xxx))`
=> fix: restore pr link expansion on non-conventional commits

crates/release_plz_core/src/changelog.rs, crates/release_plz_core/src/command/update/updater.rs, website/docs/config.md
this is a small breaking change because if you have your commit_preprocessors you won't expand the PR number anymore. You would need to add the line shown in config.md of this pr in your config.
We accept this tradeoff, we won't bump the major version for this.
=> chore: use git-cliff to expand the PR link

crates/release_plz/src/init/mod.rs
I generated the `.github/workflows/release-plz.yml` file using the `release-plz init` command, but encountered a [CI failure](https://github.com/jmjoy/comfyui-client/actions/runs/13896093222/workflow). The failure occurred because the `{}` characters in the `format!` macro are special syntax elements that require escaping.
=> fix: escape the curly braces in the template for init

crates/release_plz_core/src/copy_dir.rs
By default, `ignore::WalkBuilder::new` ignores patterns listed in the global `.gitignore`. In case a CI runner contains `.git/` in its global `.gitignore`, release-plz fails on finding the local repository and current branch after copying the repository to a temp dir.
```
...
1: failed to determine local project repository
2: cannot determine current branch
```
This PR therefore changes the code to ignore the global `.gitignore` when walking the directory tree.
=> fix: ignore global `.gitignore` when copying to tmp dir

.lycheeignore, website/docs/changelog/examples.md
I added a new example on how to configure release-plz changelog to link to diff.rs showing changes between crate versions
Closes #2097
=> chore: Add a new changelog example that uses diff.rs

crates/release_plz/tests/all/changelog.rs, crates/release_plz_core/src/changelog.rs, website/docs/changelog/examples.md, website/docs/config.md, website/docs/extra/single-changelog.md
Release-plz never sets the `v` so it's useless to remove it.
=> chore(changelog): stop trimming initial `v` in version

crates/release_plz/src/args/release.rs, crates/release_plz/src/args/update.rs, crates/release_plz/tests/all/helpers/test_context.rs, crates/release_plz_core/src/command/release.rs, crates/release_plz_core/src/command/release_pr/mod.rs, crates/release_plz_core/src/command/update/update_request.rs, crates/release_plz_core/src/git/forge.rs, crates/release_plz_core/src/git/gitea_client.rs, crates/release_plz_core/src/git/github_client.rs, crates/release_plz_core/src/git/github_graphql.rs, crates/release_plz_core/src/git/gitlab_client.rs, crates/release_plz_core/src/git/mod.rs, crates/release_plz_core/src/lib.rs, crates/release_plz_core/tests/all/helpers/comparison_test.rs, website/docs/faq.md, website/docs/github/input.md, website/docs/usage/release-pr.md, website/docs/usage/release.md
These changes rename "git backend" to "git forge" in the CLI flags, error messages and documentation and other rust files.
It adds the `alias = backend` attribute in the `Release` and `Update` structs to support retrocompatibilty.
```rs
#[arg(long, alias = "backend", value_enum, default_value_t = ReleaseGitForgeKind::Github)]
forge: ReleaseGitForgeKind,
```
Closes https://github.com/release-plz/release-plz/issues/2144
=> feat: Alias the `--backend` flag to `--forge`

Cargo.lock, crates/cargo_utils/Cargo.toml, crates/cargo_utils/src/registry.rs
Ensures `registry_index_url_from_env` correctly forms environment variable names for Cargo registry configurations, even when registry names contain dashes.
The sanitization logic now mirrors Cargo's behavior:
1. Replace sequences of dashes with an underscore.
2. Any non-alphanumeric character that is not a dash or underscore is invalid.
This fixes a bug where names like `my-registry` would not resolve to the expected `CARGO_REGISTRIES_MY_REGISTRY_INDEX`.
=> fix: align registry env var name generation with Cargo

crates/release_plz_core/src/command/update/updater.rs
Previously, release-plz could appear unresponsive for a noticeable
period (e.g., 15 seconds on a reasonably sized repository) while
calculating the diff for a package. This change adds a log message at
the start of the diff calculation to inform the user about this
potentially long-running operation.
=> chore: Indicate when diff calculation begins to avoid appearing stalled

website/docs/config.md
`changelog_config` is deprecated
=> Remove deprecated field from config example

crates/release_plz_core/src/command/release.rs, crates/release_plz_core/src/next_ver.rs
Make it easier to track via logs what logic is being used to determine whether or not a package should be published.
=> Add some more logging related to package publishing

crates/release_plz/tests/all/release_pr.rs, crates/release_plz_core/src/package_compare.rs
- **fix: do not error on README non-existence, just warn**
- Closes #2242
Added a hint to warning message
> Hint: ensure the path set in Cargo.toml points to a file that exists and is included in the crate.
=> fix: don't quit if readme doesn't exist

crates/release_plz_core/src/project.rs, tests/fixtures/non-standard-license/Cargo.toml
=> fix: allow license-file in Cargo.toml

crates/release_plz_core/src/cargo.rs, crates/release_plz_core/src/cargo_hash_kind.rs, crates/release_plz_core/src/command/release.rs
This PR introduces a fallback index field to the `CargoRegistry` struct. This fallback index is the same index using the `HashKind::Legacy` hash kind if the cargo version is 1.85+. When releasing a crate, the cli will attempt the fallback index if the primary index fails.
relates to #2340
=> feat: add a fallback index to attempt the legacy hash if the primary index fails

website/docs/github/output.md
GHA outputs are untyped, this was a slight head-scratcher without debug logs:
When using for example:
```
if: ${{ steps.release-plz.outputs.prs_created == true }}
```
Debug logs show:
```
##[debug]......Evaluating String:
##[debug]......=> 'prs_created'
##[debug]....=> 'true'
##[debug]....Evaluating Boolean:
##[debug]....=> true
##[debug]..=> false
##[debug]=> false
##[debug]Expanded: (true && ('true' == true))
^^^^^^ release-plz output
##[debug]Result: false
^^^^^  no implicit type-cast
```
Proposed solution to just not declare these as bools. Happy to come up with some other way of clarifying this.
=> docs: don't declare action outputs as boolean

crates/release_plz_core/src/command/release_pr/mod.rs, crates/release_plz_core/src/git/forge.rs
As in https://github.com/release-plz/release-plz/issues/2354, use the API to create a new branch on the remote instead of the local Git CLI.
Currently, the implementations for Gitea/GitLab seem useless, but I'll migrate commits to Gitea/GitLab, as well as GitHub, so we can merge the implementation.
ref:
- https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference
- https://docs.gitlab.com/api/branches/#create-repository-branch
- https://gitea.com/api/swagger#/repository/repoCreateBranch
=> feat: use api to create branches

Cargo.lock, Cargo.toml, crates/release_plz_core/Cargo.toml, crates/release_plz_core/src/command/release_pr/mod.rs, crates/release_plz_core/src/git/forge.rs, crates/release_plz_core/src/repo_url.rs
As in https://github.com/release-plz/release-plz/issues/2354, use the API to delete a new branch on the remote instead of the local Git CLI.
ref:
- https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#delete-a-reference
- https://docs.gitlab.com/api/branches/#delete-repository-branch
- https://gitea.com/api/swagger#/repository/repoDeleteBranch
I added `urlencoding` crate to encode branch names for GitLab/Gitea, but if it's better to stick to replacing `/` with `%2F`, I'll refactor so.
Also, since `Drop` trait doesn't support `async`, it looks messy. I think we can remove `TmpBranch` and manually handle the cleanup.
=> feat: use api to delete branches
