release-plz/release-plz

- README.md
- crates/release_plz/src/args.rs
- crates/release_plz_core/src/download.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/registry_packages.rs
> support alternative registries

- README.md
> README: update `release-plz update` gif

- crates/release_plz_core/src/update.rs
> fix: remove changelog unwrap

- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/release_pr.rs
> fix: fix changelog for release-pr

- Cargo.lock
- crates/release_plz/CHANGELOG.md
- crates/release_plz/Cargo.toml
- crates/release_plz_core/CHANGELOG.md
- crates/release_plz_core/Cargo.toml
> chore: release

- README.md
> README: update release-pr gif

- crates/release_plz/src/args.rs
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/next_ver.rs
> fix: remove all unwraps that are not in tests

- crates/git_cmd/src/lib.rs
> chore: add context to some errors

- crates/git_cmd/src/lib.rs
> chore: improve git error

- .github/workflows/docker.yml
> add docker cache

- Dockerfile
> fix: add git in dockerfile

- crates/release_plz_core/src/next_ver.rs
> chore: improve workspace members error

- Cargo.lock
- Dockerfile
> fix(Dockerfile): add cargo binary

- crates/release_plz_core/src/release_pr.rs
> write package name and version in PR name

- Cargo.lock
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/registry_packages.rs
- crates/release_plz_core/src/temp_dir.rs
> fix: create a temp directory in actions

- .github/workflows/docker.yml
I saw this in the docker cache example [here](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md). Let's see if it decreases build time.
> ci(docker): add checkout

- README.md
> add dockerhub badge

- Dockerfile
> chore(docker): don't run on rust image

- README.md
> Readme cargo release

- Cargo.lock
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/release_pr.rs
> chore: name new branch as timestamp

- Cargo.lock
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/download.rs
> add support for unpublished packages

- crates/release_plz_core/src/next_ver.rs
> generate changelog for new packages

- .github/workflows/docker.yml
Let's see if this caching strategy improves docker build time.
> ci(docker): change cache

- README.md
> chore(readme): link to GitHub action

- crates/release_plz_core/src/update.rs
> feat: update Cargo.lock

- Cargo.lock
- crates/release_plz/src/args.rs
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/github_client.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/release_pr.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
- crates/release_plz_core/tests/all/helpers/github_mock_server.rs
- crates/release_plz_core/tests/all/release_pr.rs
- crates/release_plz_core/tests/all/update.rs
> feat: close old release-plz prs

- .github/workflows/docker.yml
> fix: docker cache

- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/args/release_pr.rs
- crates/release_plz/src/args/update.rs
> chore(args): refactor

- crates/release_plz/src/args/release_pr.rs
- crates/release_plz/src/args/update.rs
> feat(cli): forbid empty values in args

- Cargo.lock
- README.md
- crates/next_version/README.md
- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/cargo.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/registry_packages.rs
- crates/release_plz_core/src/release.rs
- crates/release_plz_core/src/release_order.rs
> feat: add `release` command

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/cargo.rs
- crates/release_plz_core/src/release.rs
> Publish tag

- .github/workflows/ci.yml
> remove publish dry run step

- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/release_pr.rs
- crates/release_plz_core/src/update.rs
Fix https://github.com/MarcoIeni/release-plz/issues/93
> fix cargo update

- .github/workflows/docker.yml
> ci: build docker image on tag

- Cargo.lock
- crates/next_version/Cargo.toml
- crates/release_plz_core/Cargo.toml
> chore: remove default features from some deps

- Cargo.lock
- README.md
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/update.rs
> update local dependencies versions

- crates/next_version/Cargo.toml
> fix cargo-edit dependency

- crates/release_plz_core/src/release.rs
> chore(release): do not discard error

- .github/workflows/docker.yml
> chore: docker ci - add patterns

- .gitignore
- crates/release_plz_core/src/diff.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/package_compare.rs
- crates/release_plz_core/src/update.rs
- crates/release_plz_core/src/version.rs
> feat: update package if dependency is updated

- .github/workflows/docker.yml
> Fix docker metadata

- Cargo.lock
> chore: update Cargo lock

- .github/workflows/deny.yml
> chore: update cargo deny rust version

- .github/workflows/release-plz.yml
> chore: dogfooding

- Dockerfile
releasing release-plz failed. This should fix it.
> fix: docker - install pkg-config

- Cargo.lock
- README.md
- crates/release_plz/Cargo.toml
- crates/release_plz/src/args/update.rs
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
> feat: read custom git cliff config

- Dockerfile
> fix(dockerfile): install libssl-dev

- Cargo.lock
- crates/git_cmd/Cargo.toml
- crates/next_version/Cargo.toml
- crates/release_plz/Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/test_logs/Cargo.toml
> chore: upgrade dependencies

- crates/release_plz_core/src/github_client.rs
- crates/release_plz_core/src/release_pr.rs
Close https://github.com/MarcoIeni/release-plz/issues/135
> feat: improve PR body

- .github/workflows/deny.yml
> chore(cargo deny): remove fixed rust version

- .github/mergify.yml
> chore: automatically merge dependabot PRs

- .github/mergify.yml
> chore: automatically update all PRs

- .github/workflows/release-plz.yml
> fix(ci): generate github app token

- README.md
> README: add logo

- crates/release_plz_core/src/changelog.rs
> fix: remove link parsers

- .github/workflows/release-plz.yml
> fix(ci): clone repo with github token

- Dockerfile
> chore(ci): use latest rust for docker image

- .github/workflows/docker.yml
> fix(ci): remove docker cache

- crates/release_plz_core/src/github_client.rs
> chore: skip pr field in instrument

- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/log.rs
- crates/release_plz/src/main.rs
- crates/test_logs/src/lib.rs
> feat: add `verbose` flag

- crates/release_plz/src/args/update.rs
- crates/release_plz_core/src/next_ver.rs
> feat: add --allow-dirty flag to update command

- Cargo.lock
- crates/release_plz/Cargo.toml
- crates/release_plz_core/Cargo.toml
> chore: update clap and fake libraries

- .github/PULL_REQUEST_TEMPLATE.md
release-plz will update it when releasing
> chore(pr-template): do not require changelog update

- crates/release_plz_core/src/changelog.rs
> chore: remove unused lifetime

- Cargo.lock
- crates/next_version/Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/update.rs
- crates/release_plz_core/src/version.rs
- crates/release_plz_core/tests/all/update.rs
> update to cargo edit 10

- Cargo.lock
- crates/release_plz/Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/changelog.rs
> update git cliff to version 8

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/release_pr.rs
> fix: support symlinks

- README.md
Hey! I created the following AUR packages for installing `release-plz` from the AUR:
- https://aur.archlinux.org/packages/release-plz
- https://aur.archlinux.org/packages/release-plz-git
This PR simply updates README.md to mention these packages and give an example on how to install `release-plz` on Arch Linux.
Have a great day! 🐻
> docs(readme): add installation instructions for Arch Linux

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the pull request template to use the correct URL for contribution guidelines.
> fix(template): update broken link

- Cargo.lock
- crates/git_cmd/Cargo.toml
- crates/release_plz/Cargo.toml
- crates/release_plz_core/Cargo.toml
> update anyhow to 1.0.61

- crates/release_plz_core/src/next_ver.rs
> chore: fix clippy lint

- Cargo.lock
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/download.rs
> chore: use cargo-clone-core library

- Cargo.lock
- crates/cargo_utils/Cargo.toml
- crates/cargo_utils/src/lib.rs
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/update.rs
see https://github.com/killercup/cargo-edit/issues/820
> fix: include function removed from cargo-edit

- Cargo.lock
- deny.toml
> chore: cargo update

- Cargo.lock
- crates/release_plz/Cargo.toml
- crates/release_plz/src/args/generate_completions.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/release_pr.rs
- crates/release_plz/src/args/update.rs
> chore: update to clap v4

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/github_client.rs
- crates/release_plz_core/src/next_ver.rs
> fix: clippy lints

- crates/release_plz/src/args/release_pr.rs
> fix: github token parsing

- Cargo.lock
- crates/release_plz/src/args/update.rs
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
> fix!: remove deprecated chrono::Date

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/release.rs
Closes #138
This is a performance optimisation. If the tag existed, it means the package was already released in the registries. So the behaviour is the same.
I run this command in the release-plz repo:
> chore: don't release if the tag exists

- .github/workflows/cd.yml
- .github/workflows/ci.yml
> chore(ci): update rust-cache to v2

- README.md
> chore(readme): show release-plz users

- Cargo.lock
- crates/release_plz/Cargo.toml
- crates/release_plz/tests/completion_test.rs
> Add tests for shell completions

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/deny.yml
- .github/workflows/docker.yml
- .github/workflows/release-plz.yml
> fix(ci): use ubuntu 20

- Cargo.lock
- Cargo.toml
> chore: update toml_edit to 0.15

- crates/cargo_utils/src/registry.rs
- crates/cargo_utils/src/version.rs
- crates/release_plz_core/src/gitea_client.rs
> chore: fix additional clippy lints

- .github/workflows/book/book-cd.yml
> chore: publish book

- .github/workflows/book-cd.yml
- .github/workflows/book-ci.yml
> fix(docs): book path in ci

- docs/src/README.md
- docs/src/SUMMARY.md
- docs/src/github-action.md
- docs/src/installation.md
- docs/src/usage/README.md
- docs/src/usage/release-pr.md
- docs/src/usage/release.md
- docs/src/usage/shell-completions.md
- docs/src/usage/update.md
- docs/src/why.md
> chore: add more docs

- crates/release_plz/src/args/release.rs
- crates/release_plz_core/src/release.rs
> chore: use secret strings for tokens

- crates/release_plz/src/main.rs
> chore: make errors more visible

- crates/release_plz/src/args/release.rs
- crates/release_plz_core/src/next_ver.rs
> chore: print error kind when copying directories

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/changelog_parser.rs
- crates/release_plz_core/src/github_client.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/release.rs
> feat: add body to git release

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/src/release.rs
> fix(release): git-token is optional

- README.md
- docs/src/github-action.md
> chore: add GitHub action docs

- docs/src/github-action.md
> chore(docs): document `git_release` field

- crates/next_version/src/lib.rs
- crates/next_version/src/next_version.rs
> feat(next_version)!: don't remove build metadata

- crates/release_plz/src/args/update.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/package_compare.rs
- crates/release_plz_core/src/package_path.rs
- crates/release_plz_core/src/release.rs
- crates/release_plz_core/src/update.rs
> chore: extract manifest_dir function

- crates/release_plz_core/src/next_ver.rs
> fix: update crate on workspace dependencies change

- crates/cargo_utils/CHANGELOG.md
- crates/git_cmd/CHANGELOG.md
- crates/release_plz/CHANGELOG.md
- crates/test_logs/CHANGELOG.md
> chore: add links to changelogs

- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/registry_packages.rs
- crates/release_plz_core/src/release.rs
> feat: do not prefix crate name in tag for single crate projects

- crates/release_plz_core/src/backend.rs
- crates/release_plz_core/src/gitea_client.rs
- crates/release_plz_core/src/github_client.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/pr.rs
- crates/release_plz_core/src/release_pr.rs
> feat(release-pr): do not include the crate name if no workspace

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/release_pr.rs
> chore: fix typo in code

- crates/release_plz_core/src/update.rs
> fix: wrong log line

- crates/release_plz/src/main.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/update_checker.rs
Added Update checker continuing #429
> Feat: warn on old version

- Cargo.lock
- Cargo.toml
- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/github_client.rs
- crates/release_plz_core/src/release_pr.rs
- crates/release_plz_core/tests/all/helpers/gitea_mock_server.rs
- crates/release_plz_core/tests/all/helpers/github_mock_server.rs
- crates/release_plz_core/tests/all/release_pr.rs
Solves #280 for github. Gitea is todo
> feat: edit pr

- .github/workflows/docker-develop.yml
> chore(docker): create `develop` tag

- Dockerfile
> chore: update docker image

- Dockerfile
> fix(docker): install libcurl

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/deny.yml
- .github/workflows/docker-develop.yml
- .github/workflows/docker.yml
- .github/workflows/release-plz.yml
> chore(ci): update ubuntu

- .github/workflows/ci.yml
> fix(ci): downgrade ubuntu in tests

- .github/workflows/ci.yml
- crates/release_plz_core/src/release_pr.rs
Fix https://github.com/MarcoIeni/release-plz/pull/452#issuecomment-1406151688
> fix: when stash, include untracked files

- docs/src/usage/release-pr.md
- docs/src/usage/update.md
> chore(docs): explain edit-pr

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/release_pr.rs
> chore: improve logging

- .github/workflows/ci.yml
> chore(ci): update ubuntu in test job

- crates/release_plz_core/src/download.rs
> chore: improve log

- crates/release_plz_core/src/clone/mod.rs
- crates/release_plz_core/src/download.rs
fix https://github.com/MarcoIeni/release-plz/issues/501
> fix: handle new crate correctly

- .github/workflows/docker-develop.yml
- .github/workflows/docker.yml
> chore: update docker action

- crates/release_plz_core/src/clone/mod.rs
> chore: clone warning reports version

- crates/release_plz_core/src/next_ver.rs
> fix(release): trust github workspace dir

- crates/release_plz_core/src/release.rs
> chore: log published version

- crates/release_plz/src/args/update.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/repo_url.rs
> feat: add changelog changes to gitea

- crates/release_plz/src/args/release.rs
- crates/release_plz_core/src/release.rs
> feat(release): add cargo publish flags

- README.md
> chore(readme): add cargo clone to credits

- .github/workflows/ci.yml
> chore(ci): replace actions-rs

- .github/workflows/cd.yml
> chore: publish release-plz bin

- docs/src/SUMMARY.md
- docs/src/extra/README.md
- docs/src/extra/releasing-binaries.md
Closes https://github.com/MarcoIeni/release-plz/issues/419
> chore(docs): explain how to release binaries

- .github/workflows/ci.yml
> fix(ci): run step

- crates/release_plz/src/args/generate_completions.rs
- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/release_pr.rs
- crates/release_plz/src/args/update.rs
> clapv4-upgrades

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/release_pr.rs
- crates/release_plz_core/src/release.rs
Added the Option to create a gitea release.
> gitea release

- crates/release_plz/src/args/release.rs
- crates/release_plz_core/src/release.rs
> chore: remove unused field

- .github/workflows/cd.yml
I did some tests in https://github.com/MarcoIeni/release-plz/pull/547 and some targets are not working.
In this PR I'm disabling them.
> fix(cd): remove not working targets

- docs/src/installation.md
> chore(docs): explain how to download binary

- .github/workflows/book-cd.yml
> fix(book-cd): give permissions

- crates/git_cmd/src/lib.rs
> fix(release): trust gh workspace

- crates/release_plz/src/args/release.rs
fix https://github.com/MarcoIeni/release-plz/issues/555
This repo needs more tests 😭
> fix(release): fix github release

- docs/src/github-action.md
> chore(docs): update gh action section

- .github/workflows/cd.yml
- .markdownlint.yaml
- docs/src/extra/releasing-binaries.md
- docs/src/installation.md
- chore(docs): explain how to download binary
- wip
- chore(docs): improve binary release example
> docs cd example

- Cargo.lock
- Cargo.toml
- crates/cargo_utils/Cargo.toml
- crates/cargo_utils/src/registry.rs
A similar change was done [here](https://github.com/killercup/cargo-edit/commit/0b4bd79ed0774ac4fbf4a4a7fb1f6c9961b9133d)
> chore: update dependencies

- README.md
> chore(readme): improve search link

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
This is not needed because the action is not based on docker anymore
> chore: remove unused check

- crates/release_plz_core/src/backend.rs
- crates/release_plz_core/src/release_pr.rs
Close https://github.com/MarcoIeni/release-plz/issues/535
> fix: update pr title and body

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/semver_check.rs
> fix: remove ansi escapes

- .github/workflows/release-plz.yml
> chore(ci): install rust

- crates/next_version/src/lib.rs
- crates/next_version/src/version_increment.rs
> fix: always bump patch in 0.0.x versions

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/backend.rs
> chore: retry failing http calls

- crates/release_plz_core/src/pr.rs
Implements one of the two requests of https://github.com/MarcoIeni/release-plz/issues/592
> feat: include version in pr title for single crate

- Cargo.lock
- crates/fake_package/Cargo.toml
- crates/fake_package/src/dependency.rs
- crates/fake_package/src/lib.rs
- crates/fake_package/src/package.rs
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/release_order.rs
> chore: add fake_package crate for testing purposes

- Cargo.lock
- Cargo.toml
> fix: update to cargo 0.69

- crates/release_plz_core/src/changelog_parser.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/pr.rs
- crates/release_plz_core/src/update.rs
> feat: write changelog in pr body

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/release_pr.rs
> fix: do git fetch before rebase

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/release_pr.rs
fix https://github.com/MarcoIeni/release-plz/issues/608
> feat: detect remote

- crates/release_plz_core/src/backend.rs
> chore: gitea refactor

- deny.toml
> chore: allow cargo rustsec

- crates/release_plz/src/args/release_pr.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/src/next_ver.rs
> feat: read repo-url from config

- .github/PULL_REQUEST_TEMPLATE.md
- crates/cargo_utils/src/version.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/semver_check.rs
- crates/release_plz_core/src/update.rs
Closes https://github.com/MarcoIeni/release-plz/issues/635
> update workspace version

- docs/src/github-action.md
> chore: document how to run on schedule

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/config.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/release.rs
- crates/release_plz_core/src/semver_check.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
- docs/book.toml
- docs/src/SUMMARY.md
- docs/src/changelog-format.md
- docs/src/config.md
> feat: use package update config

- docs/src/github-action.md
docs for https://github.com/MarcoIeni/release-plz-action/pull/45
> chore(docs): remove args from github action

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/changelog_parser.rs
close https://github.com/MarcoIeni/release-plz/issues/643
> feat: detect custom header

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/config.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/package_path.rs
- crates/release_plz_core/src/release.rs
- crates/release_plz_core/src/update.rs
- docs/src/config.md
Related to https://github.com/MarcoIeni/release-plz/issues/637
> feat: allow to provide a custom changelog path

- crates/release_plz_core/src/next_ver.rs
close https://github.com/MarcoIeni/release-plz/issues/647
> fix: detect allow-dirty error

- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/release.rs
- docs/src/config.md
> fix: changelog path handling

- docs/src/SUMMARY.md
- docs/src/config.md
- docs/src/extra/README.md
- docs/src/extra/yanked-packages.md
explain how to deal with https://github.com/MarcoIeni/release-plz/issues/524
> chore(docs): how to deal with yanked packages

- docs/src/SUMMARY.md
- docs/src/extra/single-changelog.md
> chore(docs): explain how to have single changelog

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/config.rs
- crates/release_plz_core/src/release.rs
- docs/src/config.md
- docs/src/github-action.md
breaking: remove git_release cli flag. Now git releases are on by default.
close https://github.com/MarcoIeni/release-plz/issues/679
> feat!: enable git release from config

- crates/git_cmd/src/lib.rs
- crates/next_version/src/lib.rs
> chore: add test for breaking change in footer

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/config.rs
- docs/src/config.md
> chore: simplify configuration file structure

- crates/release_plz/src/config.rs
- docs/src/config.md
- docs/src/extra/single-changelog.md
> feat: add name field in configuration

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/config.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/release.rs
- docs/src/config.md
Close https://github.com/MarcoIeni/release-plz/issues/688
> fix: config package override

- docs/src/README.md
- docs/src/config.md
> chore: improve docs

- docs/src/SUMMARY.md
> chore(docs): move section

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/config.rs
- crates/release_plz_core/src/next_ver.rs
- docs/src/config.md
> chore: rename config field update_dependencies

- crates/release_plz/src/config.rs
- crates/release_plz_core/src/next_ver.rs
- docs/src/config.md
- docs/src/extra/single-changelog.md
> chore: rename config field update_changelog

- docs/src/config.md
> chore(docs): add config example

- README.md
- crates/release_plz/src/config.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/src/backend.rs
- crates/release_plz_core/src/pr.rs
- crates/release_plz_core/src/release_pr.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
- docs/src/config.md
Closes https://github.com/MarcoIeni/release-plz/issues/707
> feat: add pr labels

- docs/src/github/trigger.md
> chore: simplify further workflow docs

- docs/src/usage/README.md
> docs: add faq regarding `publish = false`

- README.md
- docs/src/usage/README.md
- docs/src/usage/release.md
> docs: improves commands description

- README.md
- docs/src/README.md
- docs/src/SUMMARY.md
- docs/src/changelog-format.md
- docs/src/usage/release.md
- docs/src/usage/update.md
> docs: improve readme

- docs/src/SUMMARY.md
- docs/src/github/update.md
> docs: how to keep action up-to-date

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
> fix(windows): downgrade cargo

- docs/src/config.md
- docs/src/extra/releasing-binaries.md
- docs/src/github/README.md
- docs/src/github/trigger.md
- docs/src/github/update.md
> docs: improve triggering further workflow section

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- docs/src/extra/releasing-binaries.md
> chore: update windows and mac ci images

- docs/src/github/trigger.md
> docs: fix typo

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/package_compare.rs
Close https://github.com/MarcoIeni/release-plz/issues/730
> fix: don't compare ignored files

- .github/mergify.yml
This change has been made by @MarcoIeni from Mergify config editor.
> ci(Mergify): skip release-plz PRs

- crates/release_plz/CHANGELOG.md
- docs/src/usage/release.md
> Fix: Typo: incorrect spelling of "false" in release.md

- CONTRIBUTING.md
> docs(contributing): no need to update changelog

- deny.toml
> chore: less noisy cargo-deny config

- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/repo_command.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/config.rs
> fix: set repo url also for release command

- docs/src/github/README.md
- docs/src/usage/release.md
> chore: improve gh action docs

- crates/release_plz_core/src/git/backend.rs
- crates/release_plz_core/src/release_pr.rs
Fix https://github.com/MarcoIeni/release-plz/issues/615
I don't know why from time to time the `git rebase` fails, but at least with this mitigation, we close the old pr and open a new one.
> fix: abort failed rebase

- crates/release_plz/src/config.rs
- crates/release_plz_core/src/next_ver.rs
- docs/src/config.md
> chore: represent semver_check config as bool

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/next_ver.rs
close https://github.com/MarcoIeni/release-plz/issues/645
> perf: run cargo-semver-check in parallel

- docs/src/usage/release-pr.md
> docs: explain you can edit PRs

- docs/src/config.md
Closes https://github.com/MarcoIeni/release-plz/issues/777
> docs: clarify `publish` config field

- docs/src/usage/release-pr.md
Document better doubts of https://github.com/MarcoIeni/release-plz/issues/770
> docs: document pr update better

- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/package_compare.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
Useful for https://github.com/MarcoIeni/release-plz/issues/778
> fix: ignore other crates' dirs

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/lock_compare.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/package_compare.rs
Close https://github.com/MarcoIeni/release-plz/issues/48
> feat: compare `Cargo.lock` changes

- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/repo_url.rs
> feat: add pr/issue link to changelog entries

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/lock_compare.rs
> perf: parse cargo lock faster

- Cargo.toml
- crates/release_plz_core/src/command/release_pr.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/pr.rs
fix https://github.com/MarcoIeni/release-plz/issues/815
> fix: update changelog correctly when workspace version specified

- docs/src/SUMMARY.md
- docs/src/semver-check.md
- docs/src/semver_check.md
Close https://github.com/MarcoIeni/release-plz/issues/811
> docs: document semver check

- README.md
- crates/release_plz/Cargo.toml
> docs: add emojis to readme

- crates/release_plz_core/src/package_compare.rs
> chore: small package comparison refactor

- docs/src/why.md
> docs: more difference with release-please

- docs/src/config.md
> docs: fix markdown link position

- docs/src/SUMMARY.md
- docs/src/faq.md
- docs/src/usage/README.md
- docs/src/usage/release-pr.md
- docs/src/usage/update.md
> docs: add faq page

- docs/book.toml
> fix(website): restore site-url

- .github/workflows/website-cd.yml
> docs(ci): fix typo

- website/docs/config.md
- website/docs/extra/releasing-binaries.md
- website/docs/usage/shell-completion.md
> docs: add admonitions

- website/src/components/HomepageFeatures/index.js
> docs: add missing space

- website/src/css/custom.css
> docs: use orange color

- website/src/pages/index.js
> docs: uppercase title

- crates/release_plz_core/src/command/update.rs
> chore: simpler error management

- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/next_ver.rs
fix https://github.com/MarcoIeni/release-plz/issues/877
> fix: update workspace version in dependencies

- tests/docker-compose.yml
fix https://github.com/MarcoIeni/release-plz/issues/901
> chore(tests): use gitea with postgres

- website/docs/config.md
- website/docs/troubleshooting.md
- website/sidebars.js
> docs: add troubleshooting section

- Cargo.lock
- Cargo.toml
> fix: release in https git repos

- .github/workflows/ci.yml
- CONTRIBUTING.md
- crates/release_plz/Cargo.toml
- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/helpers/gitea/gitea_new.rs
close https://github.com/MarcoIeni/release-plz/issues/911
see https://stackoverflow.com/questions/48583049/run-additional-tests-by-using-a-feature-flag-to-cargo-test
> chore: add feature flag to ignore docker tests

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/src/changelog.rs
> chore: update git-cliff

- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/release_pr.rs
- crates/release_plz_core/src/git/backend.rs
> chore: improve http error messages

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- crates/release_plz_core/Cargo.toml
- website/docs/usage/installation.md
> chore: static openssl

- .github/workflows/website-ci.yml
- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/main.rs
Fix https://github.com/MarcoIeni/release-plz/issues/918
> fix: allow specifying config file path

- release-plz.toml
> chore: update dependencies before release

- release-plz.toml
> chore: create GitHub release only for release-plz

- Cargo.lock
- Cargo.toml
> chore: update cargo

- .github/workflows/links.yml
> chore(ci): don't check links on release pr

- crates/release_plz_core/src/command/release.rs
> chore: extract run_cargo_publish function

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/command/release_pr.rs
fix https://github.com/MarcoIeni/release-plz/discussions/955
> feat(release-pr): sign release-plz commit

- .github/workflows/links.yml
- website/docs/extra/releasing-binaries.md
- website/docs/github/index.md
- website/docs/github/trigger.md
> docs: update github actions

- website/docs/why.md
> docs: link to release-please

- crates/release_plz/src/config.rs
- crates/release_plz_core/src/command/release.rs
- website/docs/config.md
Closes https://github.com/MarcoIeni/release-plz/issues/951
> feat: allow disabling git tag

- tests/docker-compose.yml
> chore(tests): update gitea docker image

- crates/release_plz/src/args/update.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/update.rs
Partially address https://github.com/MarcoIeni/release-plz/issues/970
> fix: don't discard error context

- .github/workflows/links.yml
- README.md
> fix(ci): don't check links in release pr

- crates/release_plz_core/src/next_ver.rs
- website/docs/config.md
- website/docs/faq.md
> fix: don't publish examples

- crates/release_plz_core/src/changelog.rs
This change makes the changelog respect the `sort_commits` setting in `git-cliff`. `git-cliff` implements this check [here](https://github.com/orhun/git-cliff/blob/c3556135f1304fbacdf3e26c5c7f1013ebbbd6f2/git-cliff/src/lib.rs#L177-L181). Unfortunately, `git-cliff` defaults to [sorting by oldest commits first](https://github.com/orhun/git-cliff/blob/c3556135f1304fbacdf3e26c5c7f1013ebbbd6f2/git-cliff/src/args.rs#L179) whereas the code here currently defaults to sorting by newest commits first. Ideally, the default behavior should match, but changing everyone's commit order who hasn't specified this setting would probably be a rather disruptive change, so I left the current default behavior alone. Open to discussion on this though.
> fix: respect git-cliff sort order

- crates/release_plz/src/config.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/git/backend.rs
- website/docs/config.md
Close https://github.com/MarcoIeni/release-plz/issues/676
> feat: add ability to create draft git release

- .github/workflows/links.yml
- .lycheeignore
> fix(ci): ignore changelog tags link check

- Cargo.lock
- Cargo.toml
- deny.toml
> chore: add "RUSTSEC-2023-0064" to allow list

- crates/release_plz_core/src/changelog_parser.rs
> fix: parse changelog header correctly

- .github/workflows/release-plz.yml
> chore(ci): use official github action

- Dockerfile
- tests/docker-compose.yml
> chore: update docker images

- website/docs/faq.md
Close https://github.com/MarcoIeni/release-plz/issues/1018
> docs: explain how to retrieve pr branch

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/release_pr.rs
> feat(args): support `GIT_TOKEN` variable (#1008)

- website/docs/github/index.md
> Fix some spelling

- crates/release_plz_core/src/copy_dir.rs
Fix https://github.com/MarcoIeni/release-plz-action/issues/89
> fix: ignore `.ignore` files

- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz_core/src/command/release_pr.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/pr.rs
> fix: use `release-plz-` rather than `release-plz/` branch prefix

- website/docs/why.md
> docs(why): mention breaking change detection

- website/docs/config.md
> docs: specify config defaults

- crates/release_plz_core/src/download.rs
> chore: use `first()` instead of `get(0)`

- crates/release_plz/tests/all/helpers/gitea/mod.rs
> chore: remove unused `pub use`

- Cargo.lock
- crates/release_plz_core/src/changelog.rs
> fix: update git-cliff

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
> docs(website): update docusaurus to v3

- crates/next_version/src/lib.rs
Closes https://github.com/MarcoIeni/release-plz/issues/1064
> docs(next-version): clarify patch increment

- crates/release_plz/src/config.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/src/command/release_pr.rs
- crates/release_plz_core/src/git/backend.rs
- crates/release_plz_core/src/pr.rs
> feat: add `pr_draft` config option

- Cargo.lock
- release-plz.toml
> fix: release-plz config file

- website/package.json
> chore(website): remove docusaurus override

- .github/workflows/ci.yml
> chore(ci): use clippy stable

- crates/release_plz_core/src/next_ver.rs
> fix: package overrides mechanism bug

- README.md
> docs(readme): rephrase users section

- crates/release_plz/src/args/update.rs
- crates/release_plz/src/config.rs
> chore: update git-cliff references

- website/docs/troubleshooting.md
> docs: explain how to debug hanging release

- website/docs/troubleshooting.md
> docs: link publish_timeout field

- .github/workflows/ci.yml
> chore(ci): test cargo-semver-checks 0.26.0

- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/next_ver.rs
> fix: pass previous version to git-cliff

- Cargo.lock
- crates/release_plz_core/Cargo.toml
> fix: internal dependency conflict

- crates/release_plz_core/src/next_ver.rs
> feat: distinguish dependency update type

- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/toml_compare.rs
fix https://github.com/MarcoIeni/release-plz/discussions/1105
> feat: support packages with git dependencies

- crates/release_plz_core/src/next_ver.rs
Closes https://github.com/MarcoIeni/release-plz/issues/1139
> feat: return error if tag exists and package isn't published

- Cargo.lock
> fix: compile on freebsd

- README.md
> docs(readme): don't mention mdbook

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
fix https://github.com/MarcoIeni/release-plz/issues/1151
> fix: restore changes introduced by `cargo package`

- website/docs/github/token.md
> docs: link pat creation steps

- website/docs/github/token.md
> docs: clarify section

- .github/workflows/release-plz.yml
- website/docs/github/token.md
> fix: change github app deprecated args

- website/src/pages/index.js
> chore(website): remove github button

- deny.toml
> chore: remove unused advisory ignore

- crates/cargo_utils/src/workspace_members.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/next_ver.rs
> refactor: simplify code

- crates/cargo_utils/src/workspace_members.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/next_ver.rs
> refactor: remove unuseful function

- .github/workflows/ci.yml
> ci: update cargo-semver-checks to 0.27

- Cargo.lock
- crates/cargo_utils/src/local_manifest.rs
- crates/cargo_utils/src/workspace_members.rs
- crates/fake_package/Cargo.toml
- crates/fake_package/src/lib.rs
- crates/fake_package/src/metadata.rs
- crates/git_cmd/src/lib.rs
- crates/release_plz/Cargo.toml
- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/repo_command.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/release_pr.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/registry_packages.rs
- crates/release_plz_core/src/release_order.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
> chore: read cargo metadata in release-plz crate

- README.md
> docs(readme): more precise cose search

- website/docs/github/token.md
> docs: fix github app instructions typo

- .github/workflows/cargo-assist.yml
> chore(ci): add cargo assist

- .github/workflows/cargo-assist.yml
cargo-assist failed here: https://github.com/orhun/release-plz/actions/runs/7380135363/job/20077177661
trying to fix
> fix(ci): cargo-assist on PRs

- .github/workflows/cargo-assist.yml
> fix(ci): fallback to default token

- .schema/latest.json
- crates/release_plz/src/args/repo_command.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/config.rs
> refactor: flatten configuration struct

- .github/workflows/cargo-assist.yml
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/copy_dir.rs
> chore: less verbose logs

- crates/release_plz_core/src/package_compare.rs
> chore: add debug statement when Cargo.toml differs

- crates/release_plz_core/src/next_ver.rs
> chore: improve public packages error message

- crates/release_plz_core/src/next_ver.rs
This PR addresses #1204.
Before this change, when traversing prior commits during an update diff, if the history started with `Cargo.lock` existing but at some point during iteration reaches a commit where the `Cargo.lock` file did not exist, an error would be encountered. Since the `Cargo.lock` path is only needed to revert to a clean state during loop iteration, I think this is a safe change to make, however let me know if there may be any edge cases I hadn't thought about.
> fix: Prevent error if Cargo.lock doesn't exist during portions of commit history

- crates/release_plz/Cargo.toml
> fix: move dependency to dev-dependencies

- CODE_OF_CONDUCT.md
- crates/release_plz_core/src/cargo.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/package_compare.rs
fix https://github.com/MarcoIeni/release-plz/discussions/1203 and maybe https://github.com/MarcoIeni/release-plz/issues/1233
> fix: support rust-toolchain.toml file

- crates/release_plz_core/src/next_ver.rs
> chore: fix tests on mac

- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/helpers/gitea/gitea_client.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz_core/src/changelog.rs
> fix: apply default changelog git config

- website/docs/usage/release-pr.md
close https://github.com/MarcoIeni/release-plz/issues/1216
> docs(release-pr): specify `-p` behavior

- website/docs/extra/single-tag.md
- website/sidebars.js
> docs: show how to create single git tag in workspace

- .schema/latest.json
- crates/release_plz/src/changelog_config.rs
- crates/release_plz/src/config.rs
fix https://github.com/MarcoIeni/release-plz/issues/696
> fix(config): deny unknown fields

- website/src/data/feedback.tsx
https://github.com/MarcoIeni/release-plz/issues/1252#issuecomment-1937894006
> docs: fix quote author name

- crates/release_plz_core/src/next_ver.rs
> refactor: simplify get_package_diff function

- Cargo.lock
- Cargo.toml
- crates/release_plz/Cargo.toml
- crates/release_plz/src/generate_schema.rs
- Highlight diff lines between existing schema and newly generated by test
- add suggestion to test error description "(Hint: if change is intentional run `cargo run -- generate-schema` to update schema.)"
> Enhance test schema_is_up_to_date

- crates/release_plz_core/src/next_ver.rs
fix https://github.com/MarcoIeni/release-plz/issues/1288
> fix: allow configuring the `release` flag

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- website/docs/extra/releasing-binaries.md
> chore(ci): bump minimum macos version to `macos-13`

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/src/clone/mod.rs
- release-plz.toml
> chore: update cargo to v0.77

- Cargo.lock
- Cargo.toml
> chore: update to wiremock 0.6.0

- tests/docker-compose.yml
> chore(tests): update docker images

- Cargo.lock
- Cargo.toml
- release-plz.toml
> chore: update crates-index to v2.6.0

- crates/release_plz_core/src/command/release.rs
> chore: don't log big release request

- Cargo.lock
- Cargo.toml
close https://github.com/MarcoIeni/release-plz/pull/1313
> fix: downgrade crates-index

- website/docs/github/advanced.md
- website/docs/github/token.md
- website/sidebars.js
> docs(gh-action): document git submodules

- Cargo.toml
- crates/cargo_utils/Cargo.toml
- crates/fake_package/Cargo.toml
- crates/git_cmd/Cargo.toml
- crates/next_version/Cargo.toml
- crates/release_plz/Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/test_logs/Cargo.toml
- fixtures/typo-in-overrides/Cargo.toml
> chore: use edition and license workspace

- crates/release_plz_core/src/command/release_pr.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/next_ver.rs
Close https://github.com/MarcoIeni/release-plz/issues/1004
> fix: allow rust project in subdir

- README.md
- website/src/pages/index.tsx
- website/src/pages/quickstart_code.mdx
> docs: add getting started

- .schema/latest.json
- crates/release_plz/src/config.rs
- crates/release_plz/tests/all/helpers/gitea/gitea_client.rs
- crates/release_plz/tests/all/release.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/tera.rs
- website/docs/config.md
> feat: allow custom `git_release_body`

- .github/workflows/cd.yml
> chore: publish binaries regardless of errors

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/release_plz/Cargo.toml
- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/init.rs
- crates/release_plz/src/init/gh.rs
- crates/release_plz/src/init/mod.rs
- crates/release_plz/src/main.rs
- website/docs/usage/index.md
- website/docs/usage/init.md
- website/sidebars.js
> feat: add `init` command

- crates/release_plz/src/init/mod.rs
> fix(init): use correct github token

- website/docs/release-plz-in-the-wild.md
- website/sidebars.js
> docs: show where release-plz is used

- crates/release_plz/Cargo.toml
> chore: fix cargo-binstall pkg-url

- Cargo.lock
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/cargo_vcs_info.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/registry_packages.rs
Close https://github.com/MarcoIeni/release-plz/issues/1369 https://github.com/MarcoIeni/release-plz/issues/1376
> fix: initialize git repo for downloaded packages

- .schema/latest.json
- Cargo.lock
- Cargo.toml
- crates/release_plz/src/changelog_config.rs
- crates/release_plz_core/src/changelog.rs
- deny.toml
See <https://github.com/MarcoIeni/release-plz/pull/1305#issuecomment-2016628117>
> chore(deps): bump git-cliff-core to v2

- .github/dependabot.yml
- Cargo.lock
- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/release_pr.rs
- crates/release_plz/src/log.rs
- crates/release_plz/src/main.rs
- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release.rs
- crates/release_plz_core/src/cargo.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/release_pr.rs
- crates/release_plz_core/src/copy_dir.rs
- crates/release_plz_core/src/git/backend.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
- website/docs/usage/release-pr.md
- website/docs/usage/release.md
required for https://github.com/MarcoIeni/release-plz-action/issues/88
> feat: add json output

- crates/release_plz/src/main.rs
- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/release.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/release_pr.rs
- website/docs/usage/release-pr.md
- website/docs/usage/release.md
> chore: edit json format output

- website/docs/github/security.md
> docs: add security risk

- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/update.rs
> fix: correctly alias `project-manifest`

- crates/release_plz_core/src/cargo.rs
> chore: don't log cargo stderr

- crates/release_plz_core/src/cargo.rs
`Command.wait` with reading stdin/stdout through pipe can cause a deadlock in a project with big amount of files (see https://stackoverflow.com/questions/64398866/why-does-bufreader-hang-when-reading-from-stderr for details).
Replace `Command.wait_with_output` with `Command.output` to prevent this when calling `cargo` command (similarly to other places in the code).
> fix: avoid potential deadlock in large repo

- website/src/data/feedback.tsx
> chore(website): add Luca's quote

- .schema/latest.json
- crates/git_cmd/src/lib.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/config.rs
- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/helpers/gitea/mod.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/git/backend.rs
- tests/docker-compose.yml
- website/docs/config.md
- website/docs/github/advanced.md
close https://github.com/MarcoIeni/release-plz/issues/1289
> feat: add `release_always` option to release on release PRs only

- crates/release_plz/src/main.rs
- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/release.rs
- crates/release_plz_core/src/command/release.rs
> fix: json output for empty results

- deny.toml
> chore: ignore gix security issue

- crates/release_plz_core/src/command/release.rs
> fix: json output of release command

- website/docs/github/output.md
- website/docs/github/quickstart.md
- website/sidebars.js
> docs: document GitHub action output

- website/docs/github/output.md
> docs: improve GitHub action output example

- .schema/latest.json
- crates/release_plz/src/config.rs
- crates/release_plz_core/src/command/release.rs
> feat: use cargo registry environment variable to authenticate in private sparse registry

- crates/git_cmd/src/lib.rs
- crates/release_plz/src/config.rs
> chore: improve uncommitted changes error message

- Cargo.toml
- crates/cargo_utils/src/manifest.rs
- crates/cargo_utils/src/workspace_members.rs
- crates/git_cmd/src/lib.rs
- crates/release_plz/src/args/release_pr.rs
- crates/release_plz/src/config.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/clone/mod.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/diff.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
> chore: add clippy lints

- Cargo.toml
- crates/cargo_utils/src/local_manifest.rs
- crates/release_plz/src/config.rs
- crates/release_plz/src/generate_schema.rs
- crates/release_plz/src/init/mod.rs
- crates/release_plz/tests/all/helpers/gitea/mod.rs
- crates/release_plz/tests/all/helpers/reqwest_utils.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release.rs
- crates/release_plz_core/src/fs_utils.rs
- crates/release_plz_core/src/lock_compare.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/pr.rs
> chore: add `uninlined_format_args`

- Cargo.toml
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/tera.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
> chore: add `needless_pass_by_value` lint

- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/pr_parser.rs
- website/docs/github/output.md
- website/docs/usage/release.md
> feat: print released prs

- website/.markdownlint.yaml
- website/docs/github/advanced.md
> docs: document how to close old release pr

- crates/release_plz_core/src/command/release_pr.rs
> chore: improve error message when updating pr

- crates/cargo_utils/src/registry.rs
- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz_core/src/clone/mod.rs
- crates/release_plz_core/src/git/github_graphql.rs
- crates/release_plz_core/src/registry_packages.rs
> chore: add more error contexts

- crates/release_plz_core/src/command/release_pr.rs
> refactor: remove duplicate line

- website/.markdownlint.yaml
- website/docs/config.md
- website/package.json
> docs: format markdown

- crates/release_plz_core/src/git/github_graphql.rs
> fix: don't add directories to github api commit

- website/docs/extra/single-changelog.md
> docs(single-changelog): add example output

- .github/workflows/ci.yml
> chore: update action-install-gh-release

- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/next_ver.rs
- website/.markdownlint.yaml
- website/docs/config.md
- website/docs/extra/single-changelog.md
> fix: multiple packages in one changelog with same version

- crates/release_plz/tests/all/changelog.rs
> chore: remove timestamp from test

- website/docs/media.md
- website/sidebars.js
> docs: add media

- website/docs/faq.md
> chore: mention the `[changelog]` config section

- deny.toml
> chore: update cargo-deny settings

- website/docs/github/quickstart.md
- website/docs/troubleshooting.md
> docs: adapt to new GitHub Action flow

- website/docs/github/token.md
> docs: improve GitHub Actions token docs

- tests/docker-compose.yml
> chore(tests): update gitea

- crates/release_plz_core/src/command/release.rs
Fixes [#1506](https://github.com/MarcoIeni/release-plz/issues/1506)
> fix: Handle CARGO_REGISTRIES_<name>_TOKEN env with uppercase

- crates/release_plz_core/src/git/backend.rs
> chore: remove dead code

- Cargo.lock
- crates/next_version/Cargo.toml
- crates/next_version/src/version_increment.rs
- crates/next_version/src/version_updater.rs
- crates/next_version/tests/all/normal.rs
> feat(next_version): support bumping version based on configurable custom pattern

- website/src/pages/pricing.md
> docs: improve call to action

- website/package-lock.json
- website/package.json
> chore: update website dependencies

- Cargo.lock
- Cargo.toml
- crates/release_plz/src/changelog_config.rs
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/tests/all/update.rs
close https://github.com/MarcoIeni/release-plz/issues/1534
> chore: update git-cliff to 2.4.0

- crates/cargo_utils/src/lib.rs
- crates/cargo_utils/src/local_manifest.rs
- crates/release_plz/src/args/manifest_command.rs
- crates/release_plz/src/args/mod.rs
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/args/repo_command.rs
- crates/release_plz/src/args/set_version.rs
- crates/release_plz/src/args/update.rs
- crates/release_plz/src/main.rs
- crates/release_plz_core/src/command/mod.rs
- crates/release_plz_core/src/command/release_pr.rs
- crates/release_plz_core/src/command/set_version.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/download.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/package_compare.rs
- crates/release_plz_core/src/semver_check.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
partially address https://github.com/MarcoIeni/release-plz/issues/704
> feat: implement set-version command

- website/docs/usage/set-version.md
- website/sidebars.js
> docs: document `set-version`

- Cargo.toml
- crates/cargo_utils/src/workspace_members.rs
- crates/release_plz_core/README.md
- crates/test_logs/README.md
> chore: add missing READMEs

- crates/release_plz/src/args/set_version.rs
- crates/release_plz/tests/all/set_version.rs
- crates/release_plz_core/src/command/set_version.rs
- tests/fixtures/set-version-in-package/CHANGELOG.md
- tests/fixtures/set-version-in-package/Cargo.toml
- tests/fixtures/set-version-in-package/src/main.rs
> feat(set-version): support single crate project

- crates/release_plz/src/args/mod.rs
- website/docs/usage/set-version.md
> docs(set-version): document single crate usage

- crates/release_plz/src/config.rs
- crates/release_plz_core/src/command/release.rs
Partially fix https://github.com/MarcoIeni/release-plz/issues/1549
> fix(release): set changelog path

- crates/release_plz_core/src/command/release.rs
Fix https://github.com/MarcoIeni/release-plz/issues/1545
> fix(release): specify package name

- crates/release_plz_core/src/changelog.rs
> chore: extract `get_changelog` function

- website/docs/github/quickstart.md
> docs(action): document new `backend` field

- .github/workflows/ci.yml
- website/docs/github/quickstart.md
> chore(ci): update cargo-semver-checks to 0.33

- .schema/latest.json
- crates/release_plz/src/config.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/git/backend.rs
- tests/docker-compose.yml
- website/docs/config.md
> feat: add `git_release_latest` configuration option

- crates/release_plz_core/src/git/backend.rs
> fix: GitHub release

- deny.toml
> Chore ignore "unmaintained crate" security vulnerability

- website/docs/changelog/index.md
- website/docs/config.md
- website/docs/github/token.md
- website/docs/usage/index.md
- website/docs/usage/release.md
- website/sidebars.js
> docs: various improvements

- crates/git_cmd/src/lib.rs
- crates/release_plz/tests/all/changelog.rs
- crates/release_plz_core/src/changelog_filler.rs
- crates/release_plz_core/src/diff.rs
- crates/release_plz_core/src/lib.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/version.rs
- website/docs/changelog/format.md
> add committer and author

- website/docs/github/output.md
Close https://github.com/MarcoIeni/release-plz/issues/1609
> docs: document how to commit files to release pr

- .github/workflows/ci.yml
> chore(ci): update cargo-semver-checks

- .github/renovate.json
- renovate.json
> chore: configure renovate to automerge

- crates/release_plz_core/src/command/release_pr.rs
> chore: fix inspect_err clippy lint

- Cargo.lock
> chore: update packages to fix security advisory

- crates/git_cmd/src/lib.rs
- crates/release_plz/src/args/update.rs
close https://github.com/MarcoIeni/release-plz/issues/1608
> fix: verify correctly if Cargo.lock is ignored and committed

- website/package-lock.json
> chore(website): update dependencies

- README.md
[Rendered](https://github.com/Veetaha/release-plz/tree/feat/banner-link)
> Make the banner image lead people straight to the website

- crates/release_plz/src/args/manifest_command.rs
> chore: improve invalid file error message

- .schema/latest.json
- crates/release_plz/src/config.rs
- crates/release_plz_core/src/next_ver.rs
- website/docs/config.md
Close https://github.com/MarcoIeni/release-plz/issues/1023
> feat: allow specifying `version_group` field in package config

- crates/release_plz_core/src/next_ver.rs
Close #1683 
the bug was introduced in https://github.com/MarcoIeni/release-plz/pull/1399
Sorry everyone 😅
If you want to contribute, it would be nice to add more tests.
If you are up for it, let me know 👍
> fix: restore semver check report

- .github/ISSUE_TEMPLATE/bug_report.md
> chore: improve issue template

- crates/release_plz_core/src/next_ver.rs
> refactor: extract function from `packages_to_update`

- crates/release_plz_core/src/next_ver.rs
> chore: add comments to package update code

- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/next_ver.rs
> refactor: improve `dependencies_to_update` fn

- crates/cargo_utils/src/local_manifest.rs
- crates/release_plz_core/src/next_ver.rs
Close https://github.com/MarcoIeni/release-plz/issues/1649
> feat: support local dependencies in workspace manifest

- Cargo.lock
- Cargo.toml
- crates/release_plz/src/changelog_config.rs
- crates/release_plz_core/src/changelog.rs
> chore: update to git-cliff 2.6

- Cargo.lock
- Cargo.toml
- crates/release_plz/src/args/release_pr.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/tests/all/helpers/comparison_test.rs
> chore: update to secrecy 10

- rustfmt.toml
> add rustfmt file

- crates/release_plz/tests/all/changelog.rs
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/diff.rs
- crates/release_plz_core/src/next_ver.rs
- website/docs/changelog/examples.md
- website/docs/changelog/format.md
> feat: add contributors username to context

- website/docs/changelog/examples.md
> docs: fix changelog template examples

- crates/release_plz_core/src/command/release.rs
> chore: fix `too_many_arguments` lint

- crates/cargo_utils/src/local_manifest.rs
- crates/release_plz/src/args/set_version.rs
- crates/release_plz/tests/all/changelog.rs
- crates/release_plz_core/src/copy_dir.rs
> chore: fix `unnecessary_lazy_evaluations`lint

- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/git/backend.rs
- crates/release_plz_core/src/pr_parser.rs
- crates/release_plz_core/src/tera.rs
- website/docs/config.md
> feat: add contributors to git release body context

- release-plz.toml
> chore: show contributors in release-plz own release

- .github/workflows/release-plz.yml
- crates/release_plz/src/init/mod.rs
- website/docs/github/advanced.md
- website/docs/github/output.md
- website/docs/github/quickstart.md
- website/docs/github/token.md
close https://github.com/MarcoIeni/release-plz-action/issues/87
> docs(github action): suggest using `concurrency`

- Dockerfile
> chore(dockerfile): update rustup

- .github/workflows/release-plz.yml
Test https://github.com/MarcoIeni/release-plz/issues/1752 internally
> chore: test running release-plz in parallel

- website/docs/extra/busy-repos.md
> docs: link relevant issue

- .github/workflows/release-plz.yml
> fix: github action workflow

- .schema/latest.json
- crates/release_plz/src/config.rs
- crates/release_plz/src/main.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/command/release_pr.rs
- crates/release_plz_core/src/pr.rs
- crates/release_plz_core/src/project.rs
- crates/release_plz_core/src/tera.rs
- website/docs/config.md
> feat: add pr_name config field

- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/git/backend.rs
- website/docs/usage/release.md
> fix: checkout on release commit

- .github/workflows/release-plz.yml
- crates/release_plz/src/init/mod.rs
- website/docs/config.md
> fix github token for the init command

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/command/release.rs
> fix release for squash commits

- .github/workflows/release-plz.yml
- crates/release_plz/src/init/mod.rs
- website/docs/github/advanced.md
- website/docs/github/output.md
- website/docs/github/quickstart.md
> fix(action): clone entire history for release

- website/docs/github/token.md
should clarify https://github.com/MarcoIeni/release-plz/issues/1779#issuecomment-2419824876
> docs(action): clarify how to run action

- crates/release_plz/src/args/update.rs
- crates/release_plz/src/main.rs
close https://github.com/MarcoIeni/release-plz/issues/1779
> chore: improve release-pr error message if token missing

- crates/release_plz_core/src/command/update.rs
- website/docs/config.md
> feat: add breaking_changes field to pr_body context

- website/docs/config.md
- website/docs/usage/release.md
> docs: document race condition when squash merging

- website/docs/github/output.md
> docs: change command used in the example

- Cargo.lock
- Cargo.toml
- crates/release_plz/Cargo.toml
- crates/release_plz/tests/all/helpers/reqwest_utils.rs
> chore: remove async_trait

- deny.toml
> chore: allow unmaintained crate

- website/src/pages/quickstart_code.mdx
> docs: add `--locked` flag in cargo install

- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/next_ver.rs
> fix: don't update changelog if version is already present

- .github/workflows/website-cd.yml
> chore: deploy website to cloudflare pages

- .github/workflows/website-cd.yml
- .github/workflows/website-ci.yml
> chore: update node version

- .github/workflows/release-plz.yml
- README.md
- crates/release_plz/src/init/mod.rs
- website/docs/github/advanced.md
- website/docs/github/input.md
- website/docs/github/output.md
- website/docs/github/quickstart.md
- website/docs/github/security.md
- website/docs/github/token.md
- website/docs/release-plz-in-the-wild.md
- website/docs/troubleshooting.md
> chore: move `MarcoIeni/release-plz-action` to `release-plz/action`

- .github/workflows/docker.yml
> fix(docker): use qemu only for arm

- .github/workflows/cd.yml
- README.md
- website/docs/release-plz-in-the-wild.md
- website/docusaurus.config.js
> fix: deploy pipeline

- .github/workflows/website-cd.yml
> fix: website deploy

- .github/workflows/website-cd.yml
> chore: deploy website to github pages too

- crates/release_plz/tests/all/release_pr.rs
> chore: test default release pr configuration

- crates/release_plz_core/src/diff.rs
- website/docs/changelog/format.md
related to https://github.com/release-plz/release-plz/issues/1866
> feat: add raw_message to commit context

- .github/workflows/cd.yml
> chore(ci): draft announcement via typefully

- crates/release_plz_core/src/next_ver.rs
> feat: warn if cargo-semver-checks is not installed

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
> chore: update Cargo.lock dependencies

- crates/release_plz_core/src/next_ver.rs
> chore: log when a release is skipped because of releas_commits regex

- .github/renovate.json5
> chore: use renovate best practices

- .github/renovate.json5
> chore: revert renovate best-practices config

- .github/workflows/cd.yml
- website/docs/extra/releasing-binaries.md
> chore: change how install-action is used

- .github/workflows/cargo-assist.yml
> chore: pin GitHub Action to test renovate

- .github/workflows/cargo-assist.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/deny.yml
- .github/workflows/docker-develop.yml
- .github/workflows/docker.yml
- .github/workflows/links.yml
- .github/workflows/release-plz.yml
- .github/workflows/website-cd.yml
- .github/workflows/website-ci.yml
In this way the renovate comment will look better because it will include the full tag
> chore: pin GitHub Actions tag

- .github/workflows/docker-develop.yml
- .github/workflows/docker.yml
> chore: pin two additional GitHub actions tag

- .github/workflows/docker.yml
> chore: pin actions/cache

- .github/workflows/cargo-assist.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/deny.yml
- .github/workflows/docker-develop.yml
- .github/workflows/docker.yml
- .github/workflows/links.yml
- .github/workflows/website-cd.yml
- .github/workflows/website-ci.yml
> chore(ci): implement some security practices

- .github/workflows/release-plz.yml
- crates/release_plz/src/init/mod.rs
- website/docs/github/output.md
- website/docs/github/quickstart.md
> chore: move permissions to workflow jobs

- .github/renovate.json5
> chore: update github actions weekly

- .github/renovate.json5
> chore: update docker compose images

- .github/renovate.json5
> fix renovate configuration

- .github/renovate.json5
> Fix schedule in renovate configuration

- .github/renovate.json5
> chore: automerge renovate bot PRs

- .github/renovate.json5
> fix(renovate): group GitHub Actions correctly

- .github/workflows/ci.yml
> chore(ci): always install the latest version of cargo-semver-checks

- .github/workflows/links.yml
- .github/workflows/pr-links.yml
> chore(ci): only check changed links in PR

- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/git/backend.rs
> chore: refactor to remove duplicate string

- .github/renovate.json5
> chore(ci): update docker compose files

- .github/workflows/pr-links.yml
> chore(ci): make pr-links workflow more secure

- website/docs/usage/index.md
> docs: list set-version in cli usage docs

- crates/release_plz_core/src/project.rs
> fix: release-plz init local dependency check

- .github/workflows/ci.yml
> chore(ci): remove macos duplicated test environment

- website/docs/config.md
> docs: document an example of changelog `tag_pattern`

- crates/git_cmd/src/lib.rs
> chore: add error messages

- crates/release_plz_core/src/next_ver.rs
> fix: don't update libraries versions on Cargo.lock update

- Cargo.lock
- Cargo.toml
- crates/next_version/Cargo.toml
- crates/next_version/src/next_version.rs
- crates/next_version/src/version_increment.rs
- crates/next_version/src/version_updater.rs
Close https://github.com/release-plz/release-plz/issues/2002
> chore: use `git-conventional` library to parse commits

- crates/release_plz_core/src/next_ver.rs
> fix: correctly detect if package contains executable

- .github/renovate.json5
> fix: docker-compose update in renovate config

- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/command/release_pr.rs
- website/docs/github/output.md
- website/docs/usage/release-pr.md
Closes https://github.com/release-plz/release-plz/issues/1903
> feat: add releases to release-pr json output

- crates/release_plz_core/src/git/backend.rs
Close https://github.com/release-plz/release-plz/issues/2036
> fix: don't fail if commit wasn't pushed to remote

- website/docs/config.md
> docs: improve release_commits example

- crates/release_plz_core/src/next_ver.rs
> fix: correctly detect if package is executable

- Cargo.lock
- Cargo.toml
- crates/release_plz/Cargo.toml
- crates/release_plz/src/config.rs
> chore: remove duration-str dependency

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/Cargo.toml
- crates/release_plz_core/src/changelog_parser.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/next_ver.rs
> chore: remove direct dipendency on lazy_static

- Cargo.lock
- Cargo.toml
- crates/test_logs/Cargo.toml
- crates/test_logs/src/lib.rs
> chore: remove direct dependency on once_cell

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
> docs: render mermaid diagrams

- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/semver_check.rs
regression started in https://github.com/release-plz/release-plz/pull/2016/
> fix: Check semver breaking changes on packages containing both library and binary

- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/pr.rs
- website/docs/config.md
> fix: show previous version in PR body

- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/pr.rs
- crates/release_plz_core/src/semver_check.rs
- website/docs/config.md
> fix: Bring back breaking change description in pr body

- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/lib.rs
> chore: hint to install cargo semver checks to run tests

- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/command/update.rs
- crates/release_plz_core/src/pr.rs
- website/docs/config.md
> Fix show in pr body when semver check passed

- crates/release_plz/src/args/mod.rs
> style: add style to the command line

- crates/release_plz/tests/all/release_pr.rs
> chore: Run some tests in CI that were ignored

- website/docusaurus.config.js
- website/src/pages/pricing.md
> docs: update socials

- crates/release_plz/tests/all/changelog.rs
- crates/release_plz/tests/all/helpers/mod.rs
- crates/release_plz/tests/all/helpers/package.rs
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release_pr.rs
test for https://github.com/release-plz/release-plz/issues/2034
> test that binary is updated if library changes

- crates/release_plz_core/src/clone/mod.rs
> fix: clippy lint

- Cargo.lock
- Cargo.toml
- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz/tests/all/set_version.rs
- crates/release_plz_core/src/cargo_hash_kind.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/lib.rs
- tests/docker-compose.yml
- tests/fixtures/set-version-in-workspace/crates/one/Cargo.toml
- tests/fixtures/set-version-in-workspace/crates/two/Cargo.toml
- tests/fixtures/typo-in-overrides/Cargo.toml
> feat: support rust 2024 edition

- crates/release_plz_core/src/command/release.rs
> fix: don't error if package already published

- .github/renovate.json5
> chore: rename renovate group

- website/docs/github/input.md
see https://github.com/release-plz/action/pull/191
> docs: document `verbose` action input variable

- .lycheeignore
> chore: don't check if x links are valid

- crates/release_plz/tests/all/changelog.rs
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/project.rs
- website/docs/extra/single-changelog.md
> feat: edit changelog order to respect release order

- .github/workflows/docker-develop.yml
- .github/workflows/docker.yml
> chore: don't use qemu for docker build

- CHANGELOG.md
- crates/cargo_utils/CHANGELOG.md
- crates/git_cmd/CHANGELOG.md
- crates/next_version/CHANGELOG.md
- crates/release_plz_core/CHANGELOG.md
- crates/test_logs/CHANGELOG.md
> chore: add new line to changelog header

- website/docs/changelog/examples.md
> docs: add missing new line in examples

- crates/release_plz/tests/all/changelog.rs
> test raw_message feature

- .schema/latest.json
- README.md
- crates/release_plz/src/args/release.rs
- crates/release_plz/src/config.rs
- website/docs/github/input.md
- website/docs/intro.md
- website/docs/usage/release-pr.md
- website/docs/usage/release.md
- website/src/components/HomepageFeatures/index.js
> docs: document GitLab support

- crates/release_plz_core/src/command/release.rs
> fix: deduplicate contributors

- website/package-lock.json
> update website dependencies

- .github/workflows/release-plz.yml
- crates/release_plz/src/init/gh.rs
- crates/release_plz/src/init/mod.rs
- website/docs/github/quickstart.md
address https://github.com/release-plz/release-plz/issues/2116
> don't run action in forks

- crates/release_plz_core/src/clone/mod.rs
read https://github.com/release-plz/release-plz/pull/2105 for the reason and full discussion
> chore: remove verbose cargo logs

- crates/release_plz_core/src/cargo.rs
> docs: explain why we use the crates_index crate

- crates/release_plz/src/init/mod.rs
> chore(init): explain how to create the PAT

- .github/workflows/cd.yml
> fix(cd): announcement draft

- website/docs/faq.md
> docs: suggest using set-version to edit the version

- .github/workflows/deny.yml
- Cargo.lock
- Cargo.toml
- crates/release_plz_core/src/copy_dir.rs
- deny.toml
> fix `last` clippy lint and ignore security vulnerabilities

- website/docs/github/token.md
> docs: update create-github-app-token version

- website/docs/changelog/examples.md
> docs: add 1.0.0 link in changelog examples

- website/docs/extra/releasing-binaries.md
- Close https://github.com/release-plz/release-plz/issues/2194
> docs: mention how to modify the example CD workflow YAML

- website/docs/config.md
Close https://github.com/release-plz/release-plz/issues/2198
> docs: Add 4th level to Config docs subheader nav

- website/docs/github/security.md
> docs: explain zizmor warning

- website/docs/github/security.md
This is wrong. see https://github.com/release-plz/release-plz/pull/2205#discussion_r2072318074
> docs: remove incorrect sentence

- crates/release_plz/src/args/mod.rs
Some docs changes inspired from https://github.com/release-plz/release-plz/pull/2072
> docs: improve command description

- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/release_pr/mod.rs
- crates/release_plz_core/src/command/update/updater.rs
- crates/release_plz_core/src/pr.rs
- crates/release_plz_core/src/project.rs
- crates/release_plz_core/src/tera.rs
fix https://github.com/release-plz/release-plz/issues/2209
> fix: propagate error if template doesn't render

- .github/workflows/links.yml
- .github/workflows/pr-links.yml
> set the github token to check links

- crates/release_plz/tests/all/release_pr.rs
- website/docs/config.md
> docs: document how to properly set `pr_name`

- crates/release_plz/src/args/mod.rs
Inspired by https://github.com/release-plz/release-plz/pull/2072/
> docs: improve command descriptions in the help menu

- crates/release_plz_core/src/command/update/updater.rs
Close https://github.com/release-plz/release-plz/issues/1739
> log when running cargo-semver-checks

- website/docs/github/security.md
Close https://github.com/release-plz/release-plz/issues/1906
> docs: explain how to pass environment variables in a secure way

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/cargo.rs
- crates/release_plz_core/src/command/update/packages_update.rs
- crates/release_plz_core/src/download.rs
- crates/release_plz_core/src/git/forge.rs
> fix clippy lints

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/release_pr/mod.rs
- crates/release_plz_core/src/command/set_version.rs
- crates/release_plz_core/src/command/update/packages_update.rs
- crates/release_plz_core/src/command/update/updater.rs
- crates/release_plz_core/src/download.rs
- crates/release_plz_core/src/package_compare.rs
- crates/release_plz_core/src/project.rs
- crates/release_plz_core/src/registry_packages.rs
- crates/release_plz_core/src/release_order.rs
- crates/release_plz_core/src/toml_compare.rs
> update cargo metadata to 0.20

- website/docs/intro.md
It should say `crates`, not `creates` :relaxed: So this only changes Markdown text.
> docs: :pencil2: small typo fix

- crates/release_plz/src/init/mod.rs
> feat(init): add support for trusted publishing

- Cargo.lock
- crates/release_plz/src/init/mod.rs
> feat(init): print settings URLs to enable trusted publishing

- README.md
- website/docs/release-plz-in-the-wild.md
> docs: add new dependency graph

- .schema/latest.json
- crates/release_plz/src/config.rs
- crates/release_plz/src/generate_schema.rs
I saw the other day this [comment](https://github.com/release-plz/release-plz/blob/main/crates/release_plz/src/generate_schema.rs#L26-L27) in the source code mentioning waiting for downstream fix. I looked at the [issue](https://github.com/GREsau/schemars/issues/229) and saw it was resolved, so I used the suggestion from the comment to implement a fix here!
Please let me know if you want this to be different or if there's anything to fix!
> feat: add $id field to schema

- crates/release_plz_core/src/command/release_pr/mod.rs
- crates/release_plz_core/src/git/forge.rs
> fix: recognize gitea-actions as bot account

- crates/release_plz/tests/all/changelog.rs
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/command/update/packages_update.rs
- crates/release_plz_core/src/command/update/updater.rs
- crates/release_plz_core/src/next_ver.rs
- crates/release_plz_core/src/pr.rs
Close https://github.com/release-plz/release-plz/issues/2307
> fix: show changelog preview in the PR body when changelog format is not standard

- .github/renovate.json5
> change renovate schedule

- .github/workflows/cargo-assist.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
> use actions-rust-lang/setup-rust-toolchain v1.14.1

- crates/git_cmd/src/lib.rs
- crates/release_plz_core/src/command/release_pr/mod.rs
> improve error messages

- crates/release_plz_core/src/command/release_pr/mod.rs
partially addresses https://github.com/release-plz/release-plz/issues/2376
> fix: delete branch only if it exists

- website/docs/github/quickstart.md
- website/docs/github/security.md
> docs: fix broken links

- crates/release_plz/tests/all/helpers/cmd.rs
- crates/release_plz/tests/all/helpers/test_context.rs
this fixes flakiness I experienced locally. Since I use `CARGO_TARGET_DIR=/Users/me/.cargo-target`
> isolate tests by running in unique cargo target dirs

- crates/release_plz/tests/all/helpers/test_context.rs
- crates/release_plz/tests/all/release_pr.rs
- crates/release_plz_core/src/changelog.rs
- crates/release_plz_core/src/changelog_parser.rs
fix https://github.com/release-plz/release-plz/issues/2390
> make changelog parsing more flexible

- crates/release_plz_core/src/command/release.rs
- crates/release_plz_core/src/command/trusted_publishing.rs
> refactor: trusted publisher constructor requests token

- crates/release_plz_core/src/command/release.rs
Close https://github.com/release-plz/release-plz/issues/2401
> feat: issue trusted publishing token once

- crates/release_plz/src/init/mod.rs
- website/docs/github/quickstart.md
Close https://github.com/release-plz/release-plz/issues/2402
> update trusted publishing initialization code

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/src/repo_url.rs
> update git-url-parse to 0.5

- .github/workflows/release-plz.yml
> configure trusted publishing workflow

- .github/workflows/cargo-assist.yml
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/deny.yml
- .github/workflows/docker-develop.yml
- .github/workflows/docker.yml
- .github/workflows/links.yml
- .github/workflows/pr-links.yml
- .github/workflows/release-plz.yml
- .github/workflows/website-cd.yml
- .github/workflows/website-ci.yml
- .github/workflows/zizmor.yml
> add zizmor to CI

- Cargo.lock
- Cargo.toml
- crates/release_plz_core/src/repo_url.rs
> update git-url-parse to v0.6.0

- .github/workflows/cargo-assist.yml
- .github/workflows/website-cd.yml
> cd: disable cache
